# Generated By: Claude Code (Claude Opus 4.6)

.PHONY: check install install-dev install-no-deps uninstall clean format format-check lint typecheck test test-verbose coverage run run-debug help

VENV_DIR ?= $(subst \,/,$(HOME))/.claude/venvs/voice
ifeq ($(OS),Windows_NT)
    PYTHON := $(VENV_DIR)/Scripts/python.exe
else
    PYTHON := $(VENV_DIR)/bin/python
endif

$(info venv: $(VENV_DIR))

check: format lint typecheck test coverage  ## Run format + lint + typecheck + test + coverage (default)

.DEFAULT_GOAL := check

$(PYTHON):
	python3 -m venv $(VENV_DIR)

install: $(PYTHON)  ## Install package into venv
	$(PYTHON) -m pip install .

install-dev: $(PYTHON)  ## Install in editable mode with dev deps
	$(PYTHON) -m pip install -e ".[dev]"

install-no-deps: $(PYTHON)  ## Install in editable mode without dependencies
	$(PYTHON) -m pip install -e . --no-deps

uninstall:  ## Uninstall package from venv
	$(PYTHON) -m pip uninstall -y claude-skill-voice

clean:  ## Remove build artifacts
	rm -rf build/ dist/ *.egg-info
	find . -type d -name __pycache__ -exec rm -r {} + 2>/dev/null || true
	find . -type f -name "*.pyc" -delete 2>/dev/null || true

format: install-dev  ## Format code with black
	$(PYTHON) -m black scripts tests

format-check: install-dev  ## Check formatting without modifying files
	$(PYTHON) -m black --check scripts tests

lint: install-dev  ## Lint with flake8
	$(PYTHON) -m flake8 --max-line-length=88 --extend-ignore=E203,W503 scripts tests

typecheck: install-dev  ## Type check with mypy
	$(PYTHON) -m mypy scripts

test: install-dev  ## Run pytest
	$(PYTHON) -m pytest

test-verbose: install-dev  ## Run pytest with verbose output
	$(PYTHON) -m pytest -v

coverage: install-dev  ## Run pytest with coverage
	$(PYTHON) -m pytest --cov=scripts --cov-report=term-missing

run:  ## Run voice.py using the venv Python
	$(PYTHON) scripts/voice.py

run-debug:  ## Run voice.py with --stream --debug to file (mirrors SKILL.md)
	$(PYTHON) scripts/voice.py --stream --debug ~/.config/claude-skill-voice/debug.log

help:  ## Show available targets
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-15s\033[0m %s\n", $$1, $$2}'
