# Generated By: Claude Code (Claude Opus 4.6)
"""Pytest conftest: mock system-level dependencies before test collection."""

import sys
from unittest.mock import MagicMock

# Mock sounddevice before any test module imports voice.py, which does
# `import sounddevice as sd` at the top level. sounddevice requires the
# PortAudio system library, which is unavailable in CI environments.
sys.modules.setdefault("sounddevice", MagicMock())
sys.modules.setdefault("_sounddevice", MagicMock())
