# Generated By: Claude Code (Claude Opus 4.6)
"""Unit tests for scripts/chunks.py — SilenceDetector."""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "scripts"))

from chunks import SilenceDetector  # noqa: E402


class TestSilenceDetector:
    """Tests for silence detection logic."""

    def _make_detector(self, **overrides):
        defaults = dict(
            threshold=0.02,
            duration_s=1.5,
            min_chunk_s=3.0,
            buffer_s=0.5,
            callback_interval_s=0.01,
        )
        defaults.update(overrides)
        return SilenceDetector(**defaults)

    def test_no_trigger_during_speech(self):
        det = self._make_detector()
        for i in range(500):
            result = det.feed(level=0.5, chunk_index=i, accumulated_s=10.0)
            assert result is None

    def test_no_trigger_before_duration_met(self):
        det = self._make_detector(duration_s=1.0, callback_interval_s=0.01)
        # 99 silent callbacks = 0.99s, just under 1.0s threshold
        for i in range(99):
            result = det.feed(level=0.0, chunk_index=i, accumulated_s=10.0)
            assert result is None

    def test_triggers_after_duration_met(self):
        det = self._make_detector(duration_s=1.0, callback_interval_s=0.01)
        # 100 silent callbacks = 1.0s, meets threshold
        for i in range(99):
            det.feed(level=0.0, chunk_index=i, accumulated_s=10.0)
        result = det.feed(level=0.0, chunk_index=99, accumulated_s=10.0)
        assert result is not None

    def test_returns_silence_onset_index(self):
        det = self._make_detector(
            duration_s=0.5, callback_interval_s=0.01, buffer_s=0.0
        )
        # 10 speech callbacks, then silence
        for i in range(10):
            det.feed(level=0.5, chunk_index=i, accumulated_s=10.0)
        # Silence starts at index 10
        for i in range(10, 60):
            result = det.feed(level=0.0, chunk_index=i, accumulated_s=10.0)
        # Should return index 10 (where silence began)
        assert result == 10

    def test_buffer_adjusts_onset_index(self):
        det = self._make_detector(
            duration_s=0.5, callback_interval_s=0.01, buffer_s=0.2
        )
        # Speech callbacks
        for i in range(100):
            det.feed(level=0.5, chunk_index=i, accumulated_s=10.0)
        # Silence starts at index 100
        for i in range(100, 150):
            result = det.feed(level=0.0, chunk_index=i, accumulated_s=10.0)
        # buffer_s=0.2, callback_interval_s=0.01 → buffer = 20 callbacks
        # Onset was at 100, minus buffer of 20 = 80... wait, buffer goes
        # the other direction: we want to INCLUDE 0.2s of silence after
        # the onset. So the boundary should be onset + buffer_callbacks.
        # onset=100, buffer=20 callbacks → boundary = 120
        # Actually: the boundary is where to CUT the chunk. We want to
        # keep buffer_s of silence at the END of the chunk (padding).
        # So cut at onset + buffer_in_callbacks = 100 + 20 = 120.
        assert result == 120

    def test_no_trigger_below_min_chunk(self):
        det = self._make_detector(
            duration_s=0.5, callback_interval_s=0.01, min_chunk_s=5.0
        )
        # Plenty of silence but only 2s accumulated
        for i in range(100):
            result = det.feed(level=0.0, chunk_index=i, accumulated_s=2.0)
        assert result is None

    def test_triggers_when_min_chunk_met(self):
        det = self._make_detector(
            duration_s=0.5,
            callback_interval_s=0.01,
            min_chunk_s=3.0,
            buffer_s=0.0,
        )
        for i in range(50):
            result = det.feed(level=0.0, chunk_index=i, accumulated_s=5.0)
        assert result is not None

    def test_no_retrigger_on_same_silence(self):
        det = self._make_detector(
            duration_s=0.5, callback_interval_s=0.01, buffer_s=0.0
        )
        triggered_count = 0
        for i in range(200):
            result = det.feed(level=0.0, chunk_index=i, accumulated_s=10.0)
            if result is not None:
                triggered_count += 1
        assert triggered_count == 1

    def test_retriggers_after_speech_resumes(self):
        det = self._make_detector(
            duration_s=0.5, callback_interval_s=0.01, buffer_s=0.0
        )
        triggers = []
        # First silence gap
        for i in range(100):
            r = det.feed(level=0.0, chunk_index=i, accumulated_s=10.0)
            if r is not None:
                triggers.append(r)
        # Speech resumes
        for i in range(100, 200):
            det.feed(level=0.5, chunk_index=i, accumulated_s=20.0)
        # Second silence gap
        for i in range(200, 300):
            r = det.feed(level=0.0, chunk_index=i, accumulated_s=30.0)
            if r is not None:
                triggers.append(r)
        assert len(triggers) == 2

    def test_reset_clears_state(self):
        det = self._make_detector(
            duration_s=0.5, callback_interval_s=0.01, buffer_s=0.0
        )
        # Partial silence (not enough to trigger)
        for i in range(30):
            det.feed(level=0.0, chunk_index=i, accumulated_s=10.0)
        det.reset()
        # After reset, need full duration again
        for i in range(30, 60):
            result = det.feed(level=0.0, chunk_index=i, accumulated_s=10.0)
        assert result is None  # only 30 callbacks, not 50

    def test_threshold_boundary_exact(self):
        det = self._make_detector(threshold=0.02)
        # Level exactly at threshold is NOT silent
        det.feed(level=0.02, chunk_index=0, accumulated_s=10.0)
        assert det._consecutive_silent == 0
        # Level just below threshold IS silent
        det.feed(level=0.019, chunk_index=1, accumulated_s=10.0)
        assert det._consecutive_silent == 1

    def test_speech_resets_consecutive_count(self):
        det = self._make_detector(duration_s=1.0, callback_interval_s=0.01)
        # 50 silent callbacks
        for i in range(50):
            det.feed(level=0.0, chunk_index=i, accumulated_s=10.0)
        assert det._consecutive_silent == 50
        # One speech callback resets
        det.feed(level=0.5, chunk_index=50, accumulated_s=10.0)
        assert det._consecutive_silent == 0
