# Generated By: Claude Code (Claude Opus 4.6)
"""Unit tests for scripts/voice.py."""

import json
import os
import sys
import tempfile
import wave
from unittest.mock import MagicMock, patch

import numpy as np
import pytest

# Add scripts to path so we can import voice
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "scripts"))

import voice  # noqa: E402
import whisper as whisper_mod  # noqa: E402


class TestHomeRelativePath:
    def test_converts_home_path(self):
        home = os.path.expanduser("~")
        result = voice._home_relative_path(os.path.join(home, "projects", "foo"))
        assert result == "~" + os.sep + "projects" + os.sep + "foo"

    def test_home_itself(self):
        home = os.path.expanduser("~")
        assert voice._home_relative_path(home) == "~"

    def test_non_home_path_unchanged(self):
        assert voice._home_relative_path("/tmp/foo") == "/tmp/foo"


class TestConfigPath:
    def test_linux_uses_xdg_config_home(self):
        with (
            patch("voice.sys.platform", "linux"),
            patch.dict(os.environ, {"XDG_CONFIG_HOME": "/custom/config"}, clear=False),
        ):
            result = voice._config_path()
        expected = os.path.join("/custom/config", "claude-skill-voice", "settings.json")
        assert result == expected

    def test_linux_defaults_to_dot_config(self):
        with (
            patch("voice.sys.platform", "linux"),
            patch.dict(os.environ, {}, clear=False),
            patch("voice.os.path.expanduser", return_value="/home/user"),
        ):
            env = os.environ.copy()
            env.pop("XDG_CONFIG_HOME", None)
            with patch.dict(os.environ, env, clear=True):
                result = voice._config_path()
        assert "claude-skill-voice" in result
        assert "settings.json" in result

    def test_windows_uses_appdata(self):
        with (
            patch("voice.sys.platform", "win32"),
            patch.dict(
                os.environ,
                {"APPDATA": "C:\\Users\\user\\AppData\\Roaming"},
                clear=False,
            ),
        ):
            result = voice._config_path()
        assert "claude-skill-voice" in result
        assert result.startswith("C:\\Users\\user\\AppData\\Roaming")


class TestConfig:
    def test_loads_empty_when_no_file(self, tmp_path):
        cfg = voice.Config(str(tmp_path / "nonexistent.json"))
        assert cfg.window_x is None
        assert cfg.window_y is None
        assert cfg.transcribe_ratio is None

    def test_loads_window_position(self, tmp_path):
        path = tmp_path / "settings.json"
        path.write_text(json.dumps({"window_x": 100, "window_y": 200}))
        cfg = voice.Config(str(path))
        assert cfg.window_x == 100
        assert cfg.window_y == 200

    def test_partial_window_position(self, tmp_path):
        path = tmp_path / "settings.json"
        path.write_text(json.dumps({"window_x": 100}))
        cfg = voice.Config(str(path))
        assert cfg.window_x == 100
        assert cfg.window_y is None

    def test_invalid_json_loads_empty(self, tmp_path):
        path = tmp_path / "settings.json"
        path.write_text("not json")
        cfg = voice.Config(str(path))
        assert cfg.window_x is None

    def test_converts_float_to_int(self, tmp_path):
        path = tmp_path / "settings.json"
        path.write_text(json.dumps({"window_x": 100.5, "window_y": 200.7}))
        cfg = voice.Config(str(path))
        assert cfg.window_x == 100
        assert cfg.window_y == 200

    def test_rejects_string_values(self, tmp_path):
        path = tmp_path / "settings.json"
        path.write_text(json.dumps({"window_x": "abc"}))
        cfg = voice.Config(str(path))
        assert cfg.window_x is None

    def test_save_creates_dirs_and_file(self, tmp_path):
        path = tmp_path / "sub" / "dir" / "settings.json"
        cfg = voice.Config(str(path))
        cfg.window_x = 150
        cfg.window_y = 300
        cfg.save()
        data = json.loads(path.read_text())
        assert data["window_x"] == 150
        assert data["window_y"] == 300

    def test_save_preserves_existing_keys(self, tmp_path):
        path = tmp_path / "settings.json"
        path.write_text(json.dumps({"other_key": "keep_me"}))
        cfg = voice.Config(str(path))
        cfg.window_x = 10
        cfg.save()
        data = json.loads(path.read_text())
        assert data["other_key"] == "keep_me"
        assert data["window_x"] == 10

    def test_save_overwrites_existing_position(self, tmp_path):
        path = tmp_path / "settings.json"
        path.write_text(json.dumps({"window_x": 1, "window_y": 2}))
        cfg = voice.Config(str(path))
        cfg.window_x = 500
        cfg.window_y = 600
        cfg.save()
        data = json.loads(path.read_text())
        assert data["window_x"] == 500
        assert data["window_y"] == 600

    def test_handles_corrupt_existing_file(self, tmp_path):
        path = tmp_path / "settings.json"
        path.write_text("not json")
        cfg = voice.Config(str(path))
        cfg.window_x = 10
        cfg.save()
        data = json.loads(path.read_text())
        assert data["window_x"] == 10

    def test_transcribe_ratio_loads(self, tmp_path):
        path = tmp_path / "settings.json"
        path.write_text(json.dumps({"transcribe_ratio": 0.045}))
        cfg = voice.Config(str(path))
        assert cfg.transcribe_ratio == pytest.approx(0.045)

    def test_transcribe_ratio_rejects_zero(self, tmp_path):
        path = tmp_path / "settings.json"
        path.write_text(json.dumps({"transcribe_ratio": 0}))
        cfg = voice.Config(str(path))
        assert cfg.transcribe_ratio is None

    def test_transcribe_ratio_rejects_negative(self, tmp_path):
        path = tmp_path / "settings.json"
        path.write_text(json.dumps({"transcribe_ratio": -0.5}))
        cfg = voice.Config(str(path))
        assert cfg.transcribe_ratio is None

    def test_transcribe_ratio_roundtrip(self, tmp_path):
        path = tmp_path / "settings.json"
        cfg = voice.Config(str(path))
        cfg.transcribe_ratio = 0.0523
        cfg.save()
        cfg2 = voice.Config(str(path))
        assert cfg2.transcribe_ratio == pytest.approx(0.0523)

    def test_transcribe_ratio_preserves_other_keys(self, tmp_path):
        path = tmp_path / "settings.json"
        path.write_text(json.dumps({"window_x": 100}))
        cfg = voice.Config(str(path))
        cfg.transcribe_ratio = 0.03
        cfg.save()
        data = json.loads(path.read_text())
        assert data["window_x"] == 100
        assert data["transcribe_ratio"] == pytest.approx(0.03)


class TestTruncatePath:
    def test_short_path_unchanged(self):
        path = "/home/user/project"
        assert voice._truncate_path(path) == path

    def test_exact_max_length_unchanged(self):
        path = "x" * voice.MAX_PATH_DISPLAY_LENGTH
        assert voice._truncate_path(path) == path

    def test_long_path_truncated(self):
        path = "x" * 100
        result = voice._truncate_path(path)
        assert result.startswith("...")
        assert len(result) == voice.MAX_PATH_DISPLAY_LENGTH

    def test_custom_max_length(self):
        path = "/a/very/long/path/that/exceeds/twenty/chars"
        result = voice._truncate_path(path, max_length=20)
        assert len(result) == 20
        assert result.startswith("...")


class TestGetDefaultInputDevice:
    def test_returns_sounddevice_default(self):
        with patch.object(voice.sd, "default") as mock_default:
            mock_default.device = (7, 3)
            result = voice._get_default_input_device()
        assert result == 7

    def test_falls_back_to_first_input_device(self):
        mock_devices = [
            {"name": "Speaker", "max_input_channels": 0},
            {"name": "Mic", "max_input_channels": 2},
        ]
        with (
            patch.object(voice.sd, "default") as mock_default,
            patch("voice.sd.query_devices", return_value=mock_devices),
        ):
            mock_default.device = (None, 0)
            result = voice._get_default_input_device()
        assert result == 1

    def test_raises_when_no_input_devices(self):
        mock_devices = [{"name": "Speaker", "max_input_channels": 0}]
        with (
            patch.object(voice.sd, "default") as mock_default,
            patch("voice.sd.query_devices", return_value=mock_devices),
        ):
            mock_default.device = (-1, 0)
            with pytest.raises(voice.RecordingError, match="No input devices"):
                voice._get_default_input_device()


class TestGetInputDevices:
    def test_filters_input_devices(self):
        mock_devices = [
            {"name": "Mic 1", "max_input_channels": 2},
            {"name": "Speaker", "max_input_channels": 0},
            {"name": "Mic 2", "max_input_channels": 1},
        ]
        with patch("voice.sd.query_devices", return_value=mock_devices):
            result = voice._get_input_devices()
        assert len(result) == 2
        assert result[0] == {"id": 0, "name": "Mic 1"}
        assert result[1] == {"id": 2, "name": "Mic 2"}

    def test_no_input_devices(self):
        mock_devices = [
            {"name": "Speaker", "max_input_channels": 0},
        ]
        with patch("voice.sd.query_devices", return_value=mock_devices):
            result = voice._get_input_devices()
        assert result == []


class TestSaveWav:
    def test_creates_valid_wav(self):
        audio_data = np.zeros(16000, dtype=np.int16)
        wav_path = voice.save_wav(audio_data)
        try:
            assert os.path.exists(wav_path)
            assert wav_path.startswith(tempfile.gettempdir())
            assert "claude_voice_" in wav_path

            with wave.open(wav_path, "rb") as wf:
                assert wf.getnchannels() == 1
                assert wf.getsampwidth() == 2
                assert wf.getframerate() == voice.SAMPLE_RATE
                assert wf.getnframes() == 16000
        finally:
            if os.path.exists(wav_path):
                os.remove(wav_path)

    def test_unique_filenames(self):
        audio_data = np.zeros(100, dtype=np.int16)
        path1 = voice.save_wav(audio_data)
        path2 = voice.save_wav(audio_data)
        try:
            assert path1 != path2
        finally:
            for p in [path1, path2]:
                if os.path.exists(p):
                    os.remove(p)


class TestTranscribe:
    def test_successful_transcription(self):
        mock_segment1 = MagicMock()
        mock_segment1.text = " Hello world "
        mock_segment2 = MagicMock()
        mock_segment2.text = " how are you "

        mock_model = MagicMock()
        mock_model.transcribe.return_value = ([mock_segment1, mock_segment2], None)

        with patch("whisper._get_or_create_model", return_value=mock_model):
            result = whisper_mod.transcribe_wav("/tmp/test.wav", model_size="tiny")

        mock_model.transcribe.assert_called_once_with("/tmp/test.wav", beam_size=5)
        assert result == "Hello world how are you"

    def test_empty_transcription(self):
        mock_model = MagicMock()
        mock_model.transcribe.return_value = ([], None)

        with patch("whisper._get_or_create_model", return_value=mock_model):
            result = whisper_mod.transcribe_wav("/tmp/test.wav")

        assert result == ""

    def test_whitespace_only_segments(self):
        mock_segment = MagicMock()
        mock_segment.text = "   "

        mock_model = MagicMock()
        mock_model.transcribe.return_value = ([mock_segment], None)

        with patch("whisper._get_or_create_model", return_value=mock_model):
            result = whisper_mod.transcribe_wav("/tmp/test.wav")

        assert result == ""

    def test_model_load_failure(self):
        with patch(
            "whisper._get_or_create_model",
            side_effect=RuntimeError("download failed"),
        ):
            with pytest.raises(RuntimeError, match="download failed"):
                whisper_mod.transcribe_wav("/tmp/test.wav")

    def test_default_model_size(self):
        mock_model = MagicMock()
        mock_model.transcribe.return_value = ([], None)

        with patch("whisper._get_or_create_model", return_value=mock_model) as mock_get:
            whisper_mod.transcribe_wav("/tmp/test.wav")

        mock_get.assert_called_once_with("small")


class TestRecordingError:
    def test_is_exception(self):
        err = voice.RecordingError("test")
        assert isinstance(err, Exception)
        assert str(err) == "test"


class TestLockAcquireError:
    def test_is_exception(self):
        err = voice.LockAcquireError("lock failed")
        assert isinstance(err, Exception)
        assert str(err) == "lock failed"


class TestIsPidAlive:
    def test_own_pid_is_alive(self):
        assert voice._is_pid_alive(os.getpid()) is True

    def test_dead_pid_is_not_alive(self):
        assert voice._is_pid_alive(999999999) is False

    def test_another_live_process_is_alive(self):
        # Use parent PID — guaranteed to be alive and not us
        ppid = os.getppid()
        assert voice._is_pid_alive(ppid) is True


class TestWriteLockFile:
    def test_creates_file_with_pid(self, tmp_path):
        lock = str(tmp_path / "voice.lock")
        voice._write_lock_file(lock, os.getpid())
        with open(lock) as f:
            assert int(f.read().strip()) == os.getpid()

    def test_raises_if_file_exists(self, tmp_path):
        lock = str(tmp_path / "voice.lock")
        voice._write_lock_file(lock, os.getpid())
        with pytest.raises(FileExistsError):
            voice._write_lock_file(lock, os.getpid())


class TestAcquireReleaseLock:
    def test_acquires_lock_on_empty_directory(self, tmp_path):
        lock = tmp_path / "voice.lock"
        with patch("voice._lock_path", return_value=str(lock)):
            voice._acquire_lock()
        assert lock.exists()
        assert lock.read_text().strip() == str(os.getpid())

    def test_release_removes_own_lock(self, tmp_path):
        lock = tmp_path / "voice.lock"
        with patch("voice._lock_path", return_value=str(lock)):
            voice._acquire_lock()
            voice._release_lock()
        assert not lock.exists()

    def test_own_pid_reacquires_silently(self, tmp_path):
        lock = tmp_path / "voice.lock"
        lock.write_text(str(os.getpid()))
        with patch("voice._lock_path", return_value=str(lock)):
            voice._acquire_lock()
        assert lock.read_text().strip() == str(os.getpid())

    def test_raises_when_held_by_another_live_process(self, tmp_path):
        lock = tmp_path / "voice.lock"
        ppid = os.getppid()  # guaranteed alive, not us
        lock.write_text(str(ppid))
        with patch("voice._lock_path", return_value=str(lock)):
            with pytest.raises(voice.LockAcquireError):
                voice._acquire_lock()

    def test_clears_stale_lock_from_dead_process(self, tmp_path):
        lock = tmp_path / "voice.lock"
        lock.write_text("999999999")  # dead PID
        with patch("voice._lock_path", return_value=str(lock)):
            voice._acquire_lock()
        assert lock.read_text().strip() == str(os.getpid())

    def test_release_does_not_remove_lock_owned_by_other(self, tmp_path):
        lock = tmp_path / "voice.lock"
        ppid = str(os.getppid())
        lock.write_text(ppid)
        with patch("voice._lock_path", return_value=str(lock)):
            voice._release_lock()
        assert lock.exists()
        assert lock.read_text().strip() == ppid

    def test_release_tolerates_missing_lockfile(self, tmp_path):
        lock = tmp_path / "nonexistent.lock"
        with patch("voice._lock_path", return_value=str(lock)):
            voice._release_lock()

    def test_release_logs_warning_when_not_owner(self, tmp_path):
        lock = tmp_path / "voice.lock"
        lock.write_text(str(os.getppid()))
        with (
            patch("voice._lock_path", return_value=str(lock)),
            patch("voice.log") as mock_log,
        ):
            voice._release_lock()
        mock_log.warning.assert_called_once()


class TestRecordingCancelled:
    def test_is_exception(self):
        err = voice.RecordingCancelled("cancelled")
        assert isinstance(err, Exception)
        assert str(err) == "cancelled"


def _mock_tk():
    """Return a set of patches that mock all tkinter widgets used by record_with_gui."""
    mock_root = MagicMock()
    mock_root.mainloop.return_value = None

    patches = {
        "tk": patch("voice.tk.Tk", return_value=mock_root),
        "stringvar": patch("voice.tk.StringVar", return_value=MagicMock()),
        "label": patch("voice.tk.Label", return_value=MagicMock()),
        "frame": patch("voice.tk.Frame", return_value=MagicMock()),
        "button": patch("voice.tk.Button", return_value=MagicMock()),
        "root": mock_root,
    }
    return patches


def _apply_tk_patches(tk_mocks):
    """Yield context managers for all patches in tk_mocks dict (skip 'root')."""
    return [v for k, v in tk_mocks.items() if k != "root"]


MOCK_DEVICE_INFO = {"name": "Test Mic", "max_input_channels": 2}


class TestRecordWithGui:
    def test_no_chunks_raises_recording_error(self):
        mock_stream = MagicMock()
        tk_mocks = _mock_tk()

        with (
            patch("voice.sd.InputStream", return_value=mock_stream),
            patch("voice.sd.query_devices", return_value=MOCK_DEVICE_INFO),
            tk_mocks["tk"],
            tk_mocks["stringvar"],
            tk_mocks["label"],
            tk_mocks["frame"],
            tk_mocks["button"],
        ):
            with pytest.raises(voice.RecordingError, match="No audio captured"):
                voice.record_with_gui("/tmp", device_id=0)

        mock_stream.stop.assert_called_once()
        mock_stream.close.assert_called_once()

    def test_stream_creation_failure(self):
        with (
            patch(
                "voice.sd.InputStream",
                side_effect=OSError("No microphone"),
            ),
            patch("voice.sd.query_devices", return_value=MOCK_DEVICE_INFO),
        ):
            with pytest.raises(SystemExit) as exc_info:
                voice.record_with_gui("/tmp", device_id=0)
            assert exc_info.value.code == voice.EXIT_ERROR

    def test_stream_cleanup_on_exception(self):
        mock_stream = MagicMock()
        tk_mocks = _mock_tk()
        tk_mocks["root"].mainloop.side_effect = RuntimeError("X11 error")

        with (
            patch("voice.sd.InputStream", return_value=mock_stream),
            patch("voice.sd.query_devices", return_value=MOCK_DEVICE_INFO),
            tk_mocks["tk"],
            tk_mocks["stringvar"],
            tk_mocks["label"],
            tk_mocks["frame"],
            tk_mocks["button"],
        ):
            with pytest.raises(RuntimeError, match="X11 error"):
                voice.record_with_gui("/tmp", device_id=0)

        mock_stream.stop.assert_called_once()
        mock_stream.close.assert_called_once()

    def test_passes_device_id_to_stream(self):
        mock_stream = MagicMock()
        tk_mocks = _mock_tk()

        with (
            patch("voice.sd.InputStream", return_value=mock_stream) as mock_cls,
            patch("voice.sd.query_devices", return_value=MOCK_DEVICE_INFO),
            tk_mocks["tk"],
            tk_mocks["stringvar"],
            tk_mocks["label"],
            tk_mocks["frame"],
            tk_mocks["button"],
        ):
            with pytest.raises(voice.RecordingError):
                voice.record_with_gui("/tmp", device_id=3)

        call_kwargs = mock_cls.call_args[1]
        assert call_kwargs["device"] == 3

    def test_resolves_default_device_when_none(self):
        mock_stream = MagicMock()
        tk_mocks = _mock_tk()

        with (
            patch("voice.sd.InputStream", return_value=mock_stream) as mock_cls,
            patch("voice._get_default_input_device", return_value=5),
            patch("voice.sd.query_devices", return_value=MOCK_DEVICE_INFO),
            tk_mocks["tk"],
            tk_mocks["stringvar"],
            tk_mocks["label"],
            tk_mocks["frame"],
            tk_mocks["button"],
        ):
            with pytest.raises(voice.RecordingError):
                voice.record_with_gui("/tmp")

        call_kwargs = mock_cls.call_args[1]
        assert call_kwargs["device"] == 5

    def test_successful_recording_returns_audio_and_root(self):
        mock_stream = MagicMock()
        tk_mocks = _mock_tk()

        captured_callback = None

        def capture_callback(**kwargs):
            nonlocal captured_callback
            captured_callback = kwargs["callback"]
            return mock_stream

        chunk = np.ones((1600, 1), dtype=np.int16)

        def fake_mainloop():
            captured_callback(chunk, 1600, None, None)

        tk_mocks["root"].mainloop.side_effect = fake_mainloop

        with (
            patch("voice.sd.InputStream", side_effect=capture_callback),
            patch("voice.sd.query_devices", return_value=MOCK_DEVICE_INFO),
            tk_mocks["tk"],
            tk_mocks["stringvar"],
            tk_mocks["label"],
            tk_mocks["frame"],
            tk_mocks["button"],
        ):
            audio_data, root = voice.record_with_gui("/tmp", device_id=0)

        assert isinstance(audio_data, np.ndarray)
        assert len(audio_data) == 1600
        assert root is tk_mocks["root"]

    def test_audio_callback_skips_when_paused(self):
        mock_stream = MagicMock()
        tk_mocks = _mock_tk()

        captured_callback = None

        def capture_callback(**kwargs):
            nonlocal captured_callback
            captured_callback = kwargs["callback"]
            return mock_stream

        chunk = np.ones((1600, 1), dtype=np.int16)

        def fake_mainloop():
            captured_callback(chunk, 1600, None, None)

        tk_mocks["root"].mainloop.side_effect = fake_mainloop

        with (
            patch("voice.sd.InputStream", side_effect=capture_callback),
            patch("voice.sd.query_devices", return_value=MOCK_DEVICE_INFO),
            tk_mocks["tk"],
            tk_mocks["stringvar"],
            tk_mocks["label"],
            tk_mocks["frame"],
            tk_mocks["button"],
        ):
            audio_data, _root = voice.record_with_gui("/tmp", device_id=0)

        assert len(audio_data) == 1600


class TestTranscribeErrorHandling:
    def test_model_load_logs_helpful_message(self):
        with (
            patch(
                "whisper._get_or_create_model",
                side_effect=RuntimeError("connection refused"),
            ),
            patch("whisper.log") as mock_log,
        ):
            with pytest.raises(RuntimeError):
                whisper_mod.transcribe_wav("/tmp/test.wav", model_size="small")

        mock_log.error.assert_called_once()
        msg = mock_log.error.call_args[0][0] % mock_log.error.call_args[0][1:]
        assert "Failed to load Whisper model 'small'" in msg
        assert "faster-whisper" in msg


@pytest.fixture(autouse=False)
def _no_lock():
    """Disable lockfile in tests that call main()."""
    with patch("voice._acquire_lock"), patch("voice._release_lock"):
        yield


def _mock_record_return(audio: np.ndarray) -> tuple[np.ndarray, MagicMock]:
    """Create a (audio_data, mock_root) tuple for mocking record_with_gui."""
    mock_root = MagicMock()
    return (audio, mock_root)


@pytest.mark.usefixtures("_no_lock")
class TestMain:
    def test_empty_transcript_prints_done_only(self, capsys):
        mock_audio = np.zeros(16000, dtype=np.int16)

        with (
            patch("sys.argv", ["voice.py"]),
            patch(
                "voice.record_with_gui",
                return_value=_mock_record_return(mock_audio),
            ),
            patch("voice.transcribe_with_progress", return_value=""),
            patch("voice.save_wav", return_value="/tmp/fake.wav"),
            patch("voice.os.path.exists", return_value=True),
            patch("voice.os.remove"),
        ):
            with pytest.raises(SystemExit) as exc_info:
                voice.main()
            assert exc_info.value.code == voice.EXIT_SUCCESS

        captured = capsys.readouterr()
        assert captured.out.strip() == "[DONE]"

    def test_recording_error_exits_nonzero(self):
        with (
            patch("sys.argv", ["voice.py"]),
            patch(
                "voice.record_with_gui",
                side_effect=voice.RecordingError("No audio captured."),
            ),
        ):
            with pytest.raises(SystemExit) as exc_info:
                voice.main()
            assert exc_info.value.code == voice.EXIT_ERROR

    def test_recording_cancelled_prints_cancel(self, capsys):
        with (
            patch("sys.argv", ["voice.py"]),
            patch(
                "voice.record_with_gui",
                side_effect=voice.RecordingCancelled("Recording cancelled."),
            ),
        ):
            with pytest.raises(SystemExit) as exc_info:
                voice.main()
            assert exc_info.value.code == voice.EXIT_SUCCESS

        captured = capsys.readouterr()
        assert captured.out.strip() == "[CANCEL]"

    def test_successful_transcript_prints_to_stdout(self, capsys):
        mock_audio = np.zeros(16000, dtype=np.int16)

        with (
            patch("sys.argv", ["voice.py"]),
            patch(
                "voice.record_with_gui",
                return_value=_mock_record_return(mock_audio),
            ),
            patch("voice.transcribe_with_progress", return_value="hello world"),
            patch("voice.save_wav", return_value="/tmp/fake.wav"),
            patch("voice.os.path.exists", return_value=True),
            patch("voice.os.remove"),
        ):
            voice.main()

        captured = capsys.readouterr()
        lines = captured.out.strip().split("\n")
        assert lines[0] == "[DONE]"
        assert lines[1] == "hello world"

    def test_wav_cleanup_on_transcription_failure(self):
        mock_audio = np.zeros(16000, dtype=np.int16)

        with (
            patch("sys.argv", ["voice.py"]),
            patch(
                "voice.record_with_gui",
                return_value=_mock_record_return(mock_audio),
            ),
            patch(
                "voice.transcribe_with_progress",
                side_effect=RuntimeError("model error"),
            ),
            patch("voice.save_wav", return_value="/tmp/fake.wav"),
            patch("voice.os.path.exists", return_value=True) as mock_exists,
            patch("voice.os.remove") as mock_remove,
        ):
            with pytest.raises(RuntimeError, match="model error"):
                voice.main()

        mock_exists.assert_called_with("/tmp/fake.wav")
        mock_remove.assert_called_with("/tmp/fake.wav")

    def test_wav_cleanup_skipped_when_save_fails(self):
        mock_audio = np.zeros(16000, dtype=np.int16)

        with (
            patch("sys.argv", ["voice.py"]),
            patch(
                "voice.record_with_gui",
                return_value=_mock_record_return(mock_audio),
            ),
            patch("voice.save_wav", side_effect=OSError("disk full")),
            patch("voice.os.remove") as mock_remove,
        ):
            with pytest.raises(OSError, match="disk full"):
                voice.main()

        mock_remove.assert_not_called()

    def test_list_devices_flag(self):
        mock_devices = [
            {"id": 0, "name": "Mic 1"},
            {"id": 2, "name": "Mic 2"},
        ]
        with (
            patch("sys.argv", ["voice.py", "--list-devices"]),
            patch("voice._get_input_devices", return_value=mock_devices),
        ):
            with pytest.raises(SystemExit) as exc_info:
                voice.main()
            assert exc_info.value.code == voice.EXIT_SUCCESS

    def test_list_devices_no_devices_exits_nonzero(self):
        with (
            patch("sys.argv", ["voice.py", "--list-devices"]),
            patch("voice._get_input_devices", return_value=[]),
        ):
            with pytest.raises(SystemExit) as exc_info:
                voice.main()
            assert exc_info.value.code == voice.EXIT_ERROR

    def test_model_flag_passed_to_transcribe(self):
        mock_audio = np.zeros(16000, dtype=np.int16)

        with (
            patch("sys.argv", ["voice.py", "--model", "tiny"]),
            patch(
                "voice.record_with_gui",
                return_value=_mock_record_return(mock_audio),
            ),
            patch(
                "voice.transcribe_with_progress", return_value="hello"
            ) as mock_transcribe,
            patch("voice.save_wav", return_value="/tmp/fake.wav"),
            patch("voice.os.path.exists", return_value=True),
            patch("voice.os.remove"),
        ):
            voice.main()

        mock_transcribe.assert_called_once()
        args, kwargs = mock_transcribe.call_args
        assert args[0] == "/tmp/fake.wav"
        assert kwargs["model_size"] == "tiny"

    def test_root_passed_to_transcribe_with_progress(self):
        mock_audio = np.zeros(16000, dtype=np.int16)
        mock_root = MagicMock()

        with (
            patch("sys.argv", ["voice.py"]),
            patch(
                "voice.record_with_gui",
                return_value=(mock_audio, mock_root),
            ),
            patch(
                "voice.transcribe_with_progress", return_value="hello"
            ) as mock_transcribe,
            patch("voice.save_wav", return_value="/tmp/fake.wav"),
            patch("voice.os.path.exists", return_value=True),
            patch("voice.os.remove"),
        ):
            voice.main()

        kwargs = mock_transcribe.call_args[1]
        assert kwargs["root"] is mock_root

    def test_root_destroyed_on_transcription_failure(self):
        mock_audio = np.zeros(16000, dtype=np.int16)
        mock_root = MagicMock()

        with (
            patch("sys.argv", ["voice.py"]),
            patch(
                "voice.record_with_gui",
                return_value=(mock_audio, mock_root),
            ),
            patch(
                "voice.transcribe_with_progress",
                side_effect=RuntimeError("model error"),
            ),
            patch("voice.save_wav", return_value="/tmp/fake.wav"),
            patch("voice.os.path.exists", return_value=True),
            patch("voice.os.remove"),
        ):
            with pytest.raises(RuntimeError, match="model error"):
                voice.main()

        mock_root.destroy.assert_called_once()

    def test_device_flag_passed_to_record(self):
        mock_audio = np.zeros(16000, dtype=np.int16)

        with (
            patch("sys.argv", ["voice.py", "--device", "5"]),
            patch(
                "voice.record_with_gui",
                return_value=_mock_record_return(mock_audio),
            ) as mock_record,
            patch("voice.transcribe_with_progress", return_value="hello"),
            patch("voice.save_wav", return_value="/tmp/fake.wav"),
            patch("voice.os.path.exists", return_value=True),
            patch("voice.os.remove"),
        ):
            voice.main()

        mock_record.assert_called_once()
        args, kwargs = mock_record.call_args
        assert args[0] == os.getcwd()
        assert kwargs["device_id"] == 5


@pytest.fixture(autouse=False)
def _reset_whisper_globals():
    """Reset whisper module globals so tests use the patched WhisperModel."""
    with (
        patch.object(whisper_mod, "_whisper_preload_started", False),
        patch.object(whisper_mod, "_WhisperModel", None),
        patch.object(whisper_mod, "_cached_model", None),
        patch.object(whisper_mod, "_cached_model_size", None),
    ):
        yield


@pytest.mark.usefixtures("_reset_whisper_globals")
class TestTranscribeProgressCallback:
    """Tests for transcribe() progress_callback parameter."""

    def _make_segments(self, timestamps):
        """Create mock segments with given (end,) timestamps."""
        segments = []
        for end_time in timestamps:
            seg = MagicMock()
            seg.text = "word"
            seg.end = end_time
            segments.append(seg)
        return segments

    def test_callback_called_with_correct_fractions(self, tmp_path):
        wav_path = str(tmp_path / "test.wav")
        # Create a 10-second WAV file
        with wave.open(wav_path, "wb") as wf:
            wf.setnchannels(1)
            wf.setsampwidth(2)
            wf.setframerate(16000)
            wf.writeframes(np.zeros(160000, dtype=np.int16).tobytes())

        segments = self._make_segments([2.5, 5.0, 10.0])
        mock_model = MagicMock()
        mock_model.transcribe.return_value = (segments, None)

        fractions = []

        with patch("whisper._get_or_create_model", return_value=mock_model):
            whisper_mod.transcribe_wav(wav_path, progress_callback=fractions.append)

        # Last segment hits 1.0 (10/10), plus explicit final 1.0 call
        assert fractions == [0.25, 0.5, 1.0, 1.0]

    def test_callback_clamped_to_1(self, tmp_path):
        wav_path = str(tmp_path / "test.wav")
        with wave.open(wav_path, "wb") as wf:
            wf.setnchannels(1)
            wf.setsampwidth(2)
            wf.setframerate(16000)
            wf.writeframes(np.zeros(80000, dtype=np.int16).tobytes())

        # Segment end time exceeds audio duration
        segments = self._make_segments([7.0])
        mock_model = MagicMock()
        mock_model.transcribe.return_value = (segments, None)

        fractions = []

        with patch("whisper._get_or_create_model", return_value=mock_model):
            whisper_mod.transcribe_wav(wav_path, progress_callback=fractions.append)

        assert fractions[0] == 1.0

    def test_final_1_0_always_sent(self, tmp_path):
        wav_path = str(tmp_path / "test.wav")
        with wave.open(wav_path, "wb") as wf:
            wf.setnchannels(1)
            wf.setsampwidth(2)
            wf.setframerate(16000)
            wf.writeframes(np.zeros(80000, dtype=np.int16).tobytes())

        segments = self._make_segments([2.5])
        mock_model = MagicMock()
        mock_model.transcribe.return_value = (segments, None)

        fractions = []

        with patch("whisper._get_or_create_model", return_value=mock_model):
            whisper_mod.transcribe_wav(wav_path, progress_callback=fractions.append)

        assert fractions[-1] == 1.0

    def test_no_callback_is_safe(self, tmp_path):
        wav_path = str(tmp_path / "test.wav")
        with wave.open(wav_path, "wb") as wf:
            wf.setnchannels(1)
            wf.setsampwidth(2)
            wf.setframerate(16000)
            wf.writeframes(np.zeros(16000, dtype=np.int16).tobytes())

        segments = self._make_segments([1.0])
        mock_model = MagicMock()
        mock_model.transcribe.return_value = (segments, None)

        with patch("whisper._get_or_create_model", return_value=mock_model):
            result = whisper_mod.transcribe_wav(wav_path)

        assert result == "word"

    def test_callback_not_called_when_wav_unreadable(self, tmp_path):
        # Use a path that doesn't exist — wave.open will fail,
        # audio_duration stays 0, so per-segment callbacks are skipped.
        wav_path = str(tmp_path / "nonexistent.wav")
        segments = self._make_segments([1.0])
        mock_model = MagicMock()
        mock_model.transcribe.return_value = (segments, None)

        fractions = []

        with patch("whisper._get_or_create_model", return_value=mock_model):
            whisper_mod.transcribe_wav(wav_path, progress_callback=fractions.append)

        # Only the final 1.0 is sent (no per-segment callbacks).
        assert fractions == [1.0]

    def test_empty_segments_still_sends_final(self, tmp_path):
        wav_path = str(tmp_path / "test.wav")
        with wave.open(wav_path, "wb") as wf:
            wf.setnchannels(1)
            wf.setsampwidth(2)
            wf.setframerate(16000)
            wf.writeframes(np.zeros(16000, dtype=np.int16).tobytes())

        mock_model = MagicMock()
        mock_model.transcribe.return_value = ([], None)

        fractions = []

        with patch("whisper._get_or_create_model", return_value=mock_model):
            whisper_mod.transcribe_wav(wav_path, progress_callback=fractions.append)

        assert fractions == [1.0]


class TestTranscribeWithProgress:
    """Tests for transcribe_with_progress() which reuses a tk.Tk root.

    These tests mock tkinter widgets and whisper.transcribe_wav but let real
    threading run. The mock mainloop returns immediately; the background
    thread completes near-instantly with a mocked transcribe.
    """

    def _make_root(self, children=None):
        mock_root = MagicMock()
        mock_root.winfo_children.return_value = children or []
        mock_root.mainloop.return_value = None
        return mock_root

    def _call(
        self, mock_root, transcribe_return="", transcribe_side_effect=None, **kwargs
    ):
        with (
            patch("voice.tk.Frame", return_value=MagicMock()),
            patch("voice.tk.Label", return_value=MagicMock()),
            patch("voice.tk.StringVar", return_value=MagicMock()),
            patch("voice.tk.Canvas", return_value=MagicMock()),
            patch(
                "voice.transcribe_wav",
                return_value=transcribe_return,
                side_effect=transcribe_side_effect,
            ) as mock_transcribe,
        ):
            result = voice.transcribe_with_progress(
                "/tmp/test.wav", root=mock_root, **kwargs
            )
            return result, mock_transcribe

    def test_clears_existing_widgets(self):
        child1, child2 = MagicMock(), MagicMock()
        mock_root = self._make_root(children=[child1, child2])

        result, _ = self._call(mock_root, transcribe_return="hello")

        child1.destroy.assert_called_once()
        child2.destroy.assert_called_once()
        assert result == "hello"

    def test_destroys_root_when_done(self):
        mock_root = self._make_root()
        self._call(mock_root, transcribe_return="result")
        mock_root.destroy.assert_called()

    def test_raises_transcription_error(self):
        mock_root = self._make_root()

        with pytest.raises(RuntimeError, match="model load failed"):
            self._call(
                mock_root,
                transcribe_side_effect=RuntimeError("model load failed"),
            )

    def test_passes_model_size_to_transcribe(self):
        mock_root = self._make_root()
        _, mock_transcribe = self._call(
            mock_root, transcribe_return="hi", model_size="tiny"
        )
        mock_transcribe.assert_called_once()
        assert mock_transcribe.call_args[1]["model_size"] == "tiny"

    def test_returns_empty_string_on_none_result(self):
        mock_root = self._make_root()
        result, _ = self._call(mock_root, transcribe_return="")
        assert result == ""

    def test_disables_window_close(self):
        mock_root = self._make_root()
        self._call(mock_root, transcribe_return="hi")

        protocol_calls = [
            c
            for c in mock_root.protocol.call_args_list
            if c[0][0] == "WM_DELETE_WINDOW"
        ]
        assert len(protocol_calls) == 1


@pytest.mark.usefixtures("_no_lock", "_reset_whisper_globals")
class TestWavInputOutput:
    """Tests for --wav-input and --wav-output flags."""

    def _make_wav(self, path, duration_seconds=1.0):
        """Create a valid WAV file at the given path."""
        n_samples = int(voice.SAMPLE_RATE * duration_seconds)
        audio = np.zeros(n_samples, dtype=np.int16)
        with wave.open(str(path), "wb") as wf:
            wf.setnchannels(voice.AUDIO_CHANNELS)
            wf.setsampwidth(voice.AUDIO_SAMPLE_WIDTH)
            wf.setframerate(voice.SAMPLE_RATE)
            wf.writeframes(audio.tobytes())

    def test_wav_input_transcribes_existing_file(self, tmp_path, capsys):
        wav_file = str(tmp_path / "test.wav")
        self._make_wav(wav_file)

        mock_model = MagicMock()
        mock_seg = MagicMock()
        mock_seg.text = "hello from file"
        mock_seg.end = 1.0
        mock_model.transcribe.return_value = ([mock_seg], None)

        with (
            patch("sys.argv", ["voice.py", "--wav-input", wav_file]),
            patch("whisper._get_or_create_model", return_value=mock_model),
        ):
            with pytest.raises(SystemExit) as exc_info:
                voice.main()
            assert exc_info.value.code == voice.EXIT_SUCCESS

        captured = capsys.readouterr()
        assert "hello from file" in captured.out

    def test_wav_input_with_model_flag(self, tmp_path, capsys):
        wav_file = str(tmp_path / "test.wav")
        self._make_wav(wav_file)

        mock_model = MagicMock()
        mock_model.transcribe.return_value = ([], None)

        with (
            patch(
                "sys.argv",
                ["voice.py", "--wav-input", wav_file, "--model", "tiny"],
            ),
            patch("whisper._get_or_create_model", return_value=mock_model) as mock_get,
        ):
            with pytest.raises(SystemExit) as exc_info:
                voice.main()
            assert exc_info.value.code == voice.EXIT_SUCCESS

        mock_get.assert_called_once_with("tiny")

    def test_wav_input_missing_file_exits_error(self):
        with patch(
            "sys.argv",
            ["voice.py", "--wav-input", "/nonexistent/file.wav"],
        ):
            with pytest.raises(SystemExit) as exc_info:
                voice.main()
            assert exc_info.value.code == voice.EXIT_ERROR

    def test_wav_input_no_status_line(self, tmp_path, capsys):
        """--wav-input output has no [DONE]/[CANCEL] status line."""
        wav_file = str(tmp_path / "test.wav")
        self._make_wav(wav_file)

        mock_model = MagicMock()
        mock_seg = MagicMock()
        mock_seg.text = "test"
        mock_seg.end = 1.0
        mock_model.transcribe.return_value = ([mock_seg], None)

        with (
            patch("sys.argv", ["voice.py", "--wav-input", wav_file]),
            patch("whisper._get_or_create_model", return_value=mock_model),
        ):
            with pytest.raises(SystemExit):
                voice.main()

        captured = capsys.readouterr()
        assert "[DONE]" not in captured.out
        assert "[CANCEL]" not in captured.out

    def test_wav_input_skips_lock(self, tmp_path):
        """--wav-input should not acquire the recording lock."""
        wav_file = str(tmp_path / "test.wav")
        self._make_wav(wav_file)

        mock_model = MagicMock()
        mock_model.transcribe.return_value = ([], None)

        with (
            patch("sys.argv", ["voice.py", "--wav-input", wav_file]),
            patch("whisper._get_or_create_model", return_value=mock_model),
            patch("voice._acquire_lock") as mock_lock,
        ):
            with pytest.raises(SystemExit):
                voice.main()

        mock_lock.assert_not_called()

    def test_wav_output_writes_to_path(self, tmp_path):
        mock_audio = np.zeros(16000, dtype=np.int16)
        mock_root = MagicMock()
        output_path = str(tmp_path / "saved.wav")

        with (
            patch(
                "sys.argv",
                ["voice.py", "--wav-output", output_path],
            ),
            patch(
                "voice.record_with_gui",
                return_value=(mock_audio, mock_root),
            ),
            patch("voice.transcribe_with_progress", return_value="hello"),
            patch("voice.save_wav_to") as mock_save,
            patch("voice.os.remove") as mock_remove,
        ):
            voice.main()

        # Writes directly to the output path
        mock_save.assert_called_once()
        assert mock_save.call_args[0][1] == os.path.abspath(output_path)
        # Does not delete the user's file
        mock_remove.assert_not_called()

    def test_wav_output_still_transcribes(self, tmp_path, capsys):
        mock_audio = np.zeros(16000, dtype=np.int16)
        mock_root = MagicMock()
        output_path = str(tmp_path / "saved.wav")

        with (
            patch(
                "sys.argv",
                ["voice.py", "--wav-output", output_path],
            ),
            patch(
                "voice.record_with_gui",
                return_value=(mock_audio, mock_root),
            ),
            patch("voice.transcribe_with_progress", return_value="hello world"),
            patch("voice.save_wav_to"),
        ):
            voice.main()

        captured = capsys.readouterr()
        lines = captured.out.strip().split("\n")
        assert lines[0] == "[DONE]"
        assert lines[1] == "hello world"
