# Generated By: Claude Code (Claude Opus 4.6)
"""Unit tests for scripts/voice.py."""

import contextlib
import os
import sys
import tempfile
import wave
from unittest.mock import MagicMock, patch

import numpy as np
import pytest

# Add scripts to path so we can import voice
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "scripts"))

import voice


class TestTruncatePath:
    def test_short_path_unchanged(self):
        path = "/home/user/project"
        assert voice._truncate_path(path) == path

    def test_exact_max_length_unchanged(self):
        path = "x" * voice.MAX_PATH_DISPLAY_LENGTH
        assert voice._truncate_path(path) == path

    def test_long_path_truncated(self):
        path = "x" * 100
        result = voice._truncate_path(path)
        assert result.startswith("...")
        assert len(result) == voice.MAX_PATH_DISPLAY_LENGTH

    def test_custom_max_length(self):
        path = "/a/very/long/path/that/exceeds/twenty/chars"
        result = voice._truncate_path(path, max_length=20)
        assert len(result) == 20
        assert result.startswith("...")


class TestGetInputDevices:
    def test_filters_input_devices(self):
        mock_devices = [
            {"name": "Mic 1", "max_input_channels": 2},
            {"name": "Speaker", "max_input_channels": 0},
            {"name": "Mic 2", "max_input_channels": 1},
        ]
        with patch("voice.sd.query_devices", return_value=mock_devices):
            result = voice._get_input_devices()
        assert len(result) == 2
        assert result[0] == {"id": 0, "name": "Mic 1"}
        assert result[1] == {"id": 2, "name": "Mic 2"}

    def test_no_input_devices(self):
        mock_devices = [
            {"name": "Speaker", "max_input_channels": 0},
        ]
        with patch("voice.sd.query_devices", return_value=mock_devices):
            result = voice._get_input_devices()
        assert result == []


class TestSaveWav:
    def test_creates_valid_wav(self):
        audio_data = np.zeros(16000, dtype=np.int16)
        wav_path = voice.save_wav(audio_data)
        try:
            assert os.path.exists(wav_path)
            assert wav_path.startswith(tempfile.gettempdir())
            assert "claude_voice_" in wav_path

            with wave.open(wav_path, "rb") as wf:
                assert wf.getnchannels() == 1
                assert wf.getsampwidth() == 2
                assert wf.getframerate() == voice.SAMPLE_RATE
                assert wf.getnframes() == 16000
        finally:
            if os.path.exists(wav_path):
                os.remove(wav_path)

    def test_unique_filenames(self):
        audio_data = np.zeros(100, dtype=np.int16)
        path1 = voice.save_wav(audio_data)
        path2 = voice.save_wav(audio_data)
        try:
            assert path1 != path2
        finally:
            for p in [path1, path2]:
                if os.path.exists(p):
                    os.remove(p)


class TestTranscribe:
    def test_successful_transcription(self):
        mock_segment1 = MagicMock()
        mock_segment1.text = " Hello world "
        mock_segment2 = MagicMock()
        mock_segment2.text = " how are you "

        mock_model = MagicMock()
        mock_model.transcribe.return_value = ([mock_segment1, mock_segment2], None)

        with patch("voice.WhisperModel", return_value=mock_model) as mock_cls:
            result = voice.transcribe("/tmp/test.wav", model_size="tiny")

        mock_cls.assert_called_once_with("tiny", device="cpu", compute_type="int8")
        mock_model.transcribe.assert_called_once_with("/tmp/test.wav", beam_size=5)
        assert result == "Hello world how are you"

    def test_empty_transcription(self):
        mock_model = MagicMock()
        mock_model.transcribe.return_value = ([], None)

        with patch("voice.WhisperModel", return_value=mock_model):
            result = voice.transcribe("/tmp/test.wav")

        assert result == ""

    def test_whitespace_only_segments(self):
        mock_segment = MagicMock()
        mock_segment.text = "   "

        mock_model = MagicMock()
        mock_model.transcribe.return_value = ([mock_segment], None)

        with patch("voice.WhisperModel", return_value=mock_model):
            result = voice.transcribe("/tmp/test.wav")

        assert result == ""

    def test_model_load_failure(self):
        with patch("voice.WhisperModel", side_effect=RuntimeError("download failed")):
            with pytest.raises(RuntimeError, match="download failed"):
                voice.transcribe("/tmp/test.wav")

    def test_default_model_size(self):
        mock_model = MagicMock()
        mock_model.transcribe.return_value = ([], None)

        with patch("voice.WhisperModel", return_value=mock_model) as mock_cls:
            voice.transcribe("/tmp/test.wav")

        mock_cls.assert_called_once_with("base", device="cpu", compute_type="int8")


class TestRecordingError:
    def test_is_exception(self):
        err = voice.RecordingError("test")
        assert isinstance(err, Exception)
        assert str(err) == "test"


def _mock_tk(*, num_devices=0):
    """Return a set of patches that mock all tkinter widgets used by record_with_gui."""
    mock_root = MagicMock()
    mock_root.mainloop.return_value = None

    patches = {
        "tk": patch("voice.tk.Tk", return_value=mock_root),
        "stringvar": patch("voice.tk.StringVar", return_value=MagicMock()),
        "label": patch("voice.tk.Label", return_value=MagicMock()),
        "frame": patch("voice.tk.Frame", return_value=MagicMock()),
        "button": patch("voice.tk.Button", return_value=MagicMock()),
        "root": mock_root,
    }
    if num_devices > 1:
        patches["combobox"] = patch(
            "voice.ttk.Combobox", return_value=MagicMock()
        )
    return patches


def _apply_tk_patches(tk_mocks):
    """Yield context managers for all patches in tk_mocks dict (skip 'root')."""
    return [v for k, v in tk_mocks.items() if k != "root"]


class TestRecordWithGui:
    def test_no_chunks_raises_recording_error(self):
        mock_stream = MagicMock()
        tk_mocks = _mock_tk()

        with (
            patch("voice.sd.InputStream", return_value=mock_stream),
            tk_mocks["tk"],
            tk_mocks["stringvar"],
            tk_mocks["label"],
            tk_mocks["frame"],
            tk_mocks["button"],
            patch("voice._get_input_devices", return_value=[]),
        ):
            with pytest.raises(voice.RecordingError, match="No audio captured"):
                voice.record_with_gui("/tmp")

        mock_stream.stop.assert_called_once()
        mock_stream.close.assert_called_once()

    def test_stream_creation_failure(self):
        with patch(
            "voice.sd.InputStream",
            side_effect=OSError("No microphone"),
        ):
            with pytest.raises(SystemExit) as exc_info:
                voice.record_with_gui("/tmp")
            assert exc_info.value.code == 1

    def test_stream_cleanup_on_exception(self):
        mock_stream = MagicMock()
        tk_mocks = _mock_tk()
        tk_mocks["root"].mainloop.side_effect = RuntimeError("X11 error")

        with (
            patch("voice.sd.InputStream", return_value=mock_stream),
            tk_mocks["tk"],
            tk_mocks["stringvar"],
            tk_mocks["label"],
            tk_mocks["frame"],
            tk_mocks["button"],
            patch("voice._get_input_devices", return_value=[]),
        ):
            with pytest.raises(RuntimeError, match="X11 error"):
                voice.record_with_gui("/tmp")

        mock_stream.stop.assert_called_once()
        mock_stream.close.assert_called_once()

    def test_passes_device_id_to_stream(self):
        mock_stream = MagicMock()
        tk_mocks = _mock_tk()

        with (
            patch("voice.sd.InputStream", return_value=mock_stream) as mock_cls,
            tk_mocks["tk"],
            tk_mocks["stringvar"],
            tk_mocks["label"],
            tk_mocks["frame"],
            tk_mocks["button"],
            patch("voice._get_input_devices", return_value=[]),
        ):
            with pytest.raises(voice.RecordingError):
                voice.record_with_gui("/tmp", device_id=3)

        call_kwargs = mock_cls.call_args[1]
        assert call_kwargs["device"] == 3

    def test_successful_recording_returns_audio(self):
        """Test the happy path where audio chunks are captured."""
        mock_stream = MagicMock()
        tk_mocks = _mock_tk()

        # Simulate the audio callback being invoked during mainloop
        captured_callback = None

        def capture_callback(**kwargs):
            nonlocal captured_callback
            captured_callback = kwargs["callback"]
            return mock_stream

        chunk = np.ones((1600, 1), dtype=np.int16)

        def fake_mainloop():
            # Simulate audio callback being called during recording
            captured_callback(chunk, 1600, None, None)

        tk_mocks["root"].mainloop.side_effect = fake_mainloop

        with (
            patch("voice.sd.InputStream", side_effect=capture_callback),
            tk_mocks["tk"],
            tk_mocks["stringvar"],
            tk_mocks["label"],
            tk_mocks["frame"],
            tk_mocks["button"],
            patch("voice._get_input_devices", return_value=[]),
        ):
            result = voice.record_with_gui("/tmp")

        assert isinstance(result, np.ndarray)
        assert len(result) == 1600

    def test_device_selector_shown_with_multiple_devices(self):
        """Test GUI construction with multiple input devices shows combo box."""
        mock_stream = MagicMock()
        tk_mocks = _mock_tk(num_devices=2)
        devices = [
            {"id": 0, "name": "Mic 1"},
            {"id": 2, "name": "Mic 2"},
        ]

        with contextlib.ExitStack() as stack:
            stack.enter_context(
                patch("voice.sd.InputStream", return_value=mock_stream)
            )
            for p in _apply_tk_patches(tk_mocks):
                stack.enter_context(p)
            stack.enter_context(
                patch("voice._get_input_devices", return_value=devices)
            )
            with pytest.raises(voice.RecordingError):
                voice.record_with_gui("/tmp")

    def test_audio_callback_skips_when_paused(self):
        """Test that audio callback does not append chunks when paused."""
        mock_stream = MagicMock()
        tk_mocks = _mock_tk()

        captured_callback = None

        def capture_callback(**kwargs):
            nonlocal captured_callback
            captured_callback = kwargs["callback"]
            return mock_stream

        chunk = np.ones((1600, 1), dtype=np.int16)

        # We need to test the paused state. Since paused is a closure variable,
        # we can't set it directly. Instead we test via the callback behavior
        # by checking that the callback respects the recording flag.
        def fake_mainloop():
            # First call while recording
            captured_callback(chunk, 1600, None, None)

        tk_mocks["root"].mainloop.side_effect = fake_mainloop

        with (
            patch("voice.sd.InputStream", side_effect=capture_callback),
            tk_mocks["tk"],
            tk_mocks["stringvar"],
            tk_mocks["label"],
            tk_mocks["frame"],
            tk_mocks["button"],
            patch("voice._get_input_devices", return_value=[]),
        ):
            result = voice.record_with_gui("/tmp")

        # Only one chunk was captured
        assert len(result) == 1600


class TestTranscribeErrorHandling:
    def test_model_load_prints_helpful_message(self, capsys):
        with patch(
            "voice.WhisperModel",
            side_effect=RuntimeError("connection refused"),
        ):
            with pytest.raises(RuntimeError):
                voice.transcribe("/tmp/test.wav", model_size="small")

        captured = capsys.readouterr()
        assert "Failed to load Whisper model 'small'" in captured.err
        assert "faster-whisper" in captured.err


class TestMain:
    def test_empty_transcript_exits_nonzero(self):
        mock_audio = np.zeros(16000, dtype=np.int16)

        with (
            patch("sys.argv", ["voice.py"]),
            patch("voice.record_with_gui", return_value=mock_audio),
            patch("voice.transcribe", return_value=""),
            patch("voice.save_wav", return_value="/tmp/fake.wav"),
            patch("voice.os.path.exists", return_value=True),
            patch("voice.os.remove"),
        ):
            with pytest.raises(SystemExit) as exc_info:
                voice.main()
            assert exc_info.value.code == 1

    def test_recording_error_exits_nonzero(self):
        with (
            patch("sys.argv", ["voice.py"]),
            patch(
                "voice.record_with_gui",
                side_effect=voice.RecordingError("No audio captured."),
            ),
        ):
            with pytest.raises(SystemExit) as exc_info:
                voice.main()
            assert exc_info.value.code == 1

    def test_successful_transcript_prints_to_stdout(self, capsys):
        mock_audio = np.zeros(16000, dtype=np.int16)

        with (
            patch("sys.argv", ["voice.py"]),
            patch("voice.record_with_gui", return_value=mock_audio),
            patch("voice.transcribe", return_value="hello world"),
            patch("voice.save_wav", return_value="/tmp/fake.wav"),
            patch("voice.os.path.exists", return_value=True),
            patch("voice.os.remove"),
        ):
            voice.main()

        captured = capsys.readouterr()
        assert captured.out.strip() == "hello world"

    def test_wav_cleanup_on_transcription_failure(self):
        mock_audio = np.zeros(16000, dtype=np.int16)

        with (
            patch("sys.argv", ["voice.py"]),
            patch("voice.record_with_gui", return_value=mock_audio),
            patch("voice.transcribe", side_effect=RuntimeError("model error")),
            patch("voice.save_wav", return_value="/tmp/fake.wav"),
            patch("voice.os.path.exists", return_value=True) as mock_exists,
            patch("voice.os.remove") as mock_remove,
        ):
            with pytest.raises(RuntimeError, match="model error"):
                voice.main()

        mock_exists.assert_called_with("/tmp/fake.wav")
        mock_remove.assert_called_with("/tmp/fake.wav")

    def test_wav_cleanup_skipped_when_save_fails(self):
        mock_audio = np.zeros(16000, dtype=np.int16)

        with (
            patch("sys.argv", ["voice.py"]),
            patch("voice.record_with_gui", return_value=mock_audio),
            patch("voice.save_wav", side_effect=OSError("disk full")),
            patch("voice.os.remove") as mock_remove,
        ):
            with pytest.raises(OSError, match="disk full"):
                voice.main()

        mock_remove.assert_not_called()

    def test_list_devices_flag(self):
        mock_devices = [
            {"id": 0, "name": "Mic 1"},
            {"id": 2, "name": "Mic 2"},
        ]
        with (
            patch("sys.argv", ["voice.py", "--list-devices"]),
            patch("voice._get_input_devices", return_value=mock_devices),
        ):
            with pytest.raises(SystemExit) as exc_info:
                voice.main()
            assert exc_info.value.code == 0

    def test_list_devices_no_devices_exits_nonzero(self):
        with (
            patch("sys.argv", ["voice.py", "--list-devices"]),
            patch("voice._get_input_devices", return_value=[]),
        ):
            with pytest.raises(SystemExit) as exc_info:
                voice.main()
            assert exc_info.value.code == 1

    def test_model_flag_passed_to_transcribe(self):
        mock_audio = np.zeros(16000, dtype=np.int16)

        with (
            patch("sys.argv", ["voice.py", "--model", "tiny"]),
            patch("voice.record_with_gui", return_value=mock_audio),
            patch("voice.transcribe", return_value="hello") as mock_transcribe,
            patch("voice.save_wav", return_value="/tmp/fake.wav"),
            patch("voice.os.path.exists", return_value=True),
            patch("voice.os.remove"),
        ):
            voice.main()

        mock_transcribe.assert_called_once_with("/tmp/fake.wav", model_size="tiny")

    def test_device_flag_passed_to_record(self):
        mock_audio = np.zeros(16000, dtype=np.int16)

        with (
            patch("sys.argv", ["voice.py", "--device", "5"]),
            patch("voice.record_with_gui", return_value=mock_audio) as mock_record,
            patch("voice.transcribe", return_value="hello"),
            patch("voice.save_wav", return_value="/tmp/fake.wav"),
            patch("voice.os.path.exists", return_value=True),
            patch("voice.os.remove"),
        ):
            voice.main()

        mock_record.assert_called_once_with(
            os.getcwd(), device_id=5
        )
