# Generated By: Claude Code (Claude Opus 4.6)
"""Unit tests for scripts/chunks.py — SilenceDetector and ChunkManager."""

import os
import sys
from unittest.mock import patch

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "scripts"))

from chunks import ChunkManager, SilenceDetector, trim_silence  # noqa: E402


class TestSilenceDetector:
    """Tests for silence detection logic."""

    def _make_detector(self, **overrides):
        defaults = dict(
            threshold=0.08,
            duration_s=1.0,
            min_chunk_s=1.0,
            buffer_s=0.5,
            callback_interval_s=0.01,
        )
        defaults.update(overrides)
        return SilenceDetector(**defaults)

    def test_no_trigger_during_speech(self):
        det = self._make_detector()
        for i in range(500):
            result = det.feed(level=0.5, chunk_index=i, accumulated_s=10.0)
            assert result is None

    def test_no_trigger_before_duration_met(self):
        det = self._make_detector(duration_s=1.0, callback_interval_s=0.01)
        # 99 silent callbacks = 0.99s, just under 1.0s threshold
        for i in range(99):
            result = det.feed(level=0.0, chunk_index=i, accumulated_s=10.0)
            assert result is None

    def test_triggers_after_duration_met(self):
        det = self._make_detector(duration_s=1.0, callback_interval_s=0.01)
        # 100 silent callbacks = 1.0s, meets threshold
        for i in range(99):
            det.feed(level=0.0, chunk_index=i, accumulated_s=10.0)
        result = det.feed(level=0.0, chunk_index=99, accumulated_s=10.0)
        assert result is not None

    def test_returns_silence_onset_index(self):
        det = self._make_detector(
            duration_s=0.5, callback_interval_s=0.01, buffer_s=0.0
        )
        # 10 speech callbacks, then silence
        for i in range(10):
            det.feed(level=0.5, chunk_index=i, accumulated_s=10.0)
        # Silence starts at index 10
        for i in range(10, 60):
            result = det.feed(level=0.0, chunk_index=i, accumulated_s=10.0)
        # Should return index 10 (where silence began)
        assert result == 10

    def test_buffer_adjusts_onset_index(self):
        det = self._make_detector(
            duration_s=0.5, callback_interval_s=0.01, buffer_s=0.2
        )
        # Speech callbacks
        for i in range(100):
            det.feed(level=0.5, chunk_index=i, accumulated_s=10.0)
        # Silence starts at index 100
        for i in range(100, 150):
            result = det.feed(level=0.0, chunk_index=i, accumulated_s=10.0)
        # buffer_s=0.2, callback_interval_s=0.01 → buffer = 20 callbacks
        # Onset was at 100, minus buffer of 20 = 80... wait, buffer goes
        # the other direction: we want to INCLUDE 0.2s of silence after
        # the onset. So the boundary should be onset + buffer_callbacks.
        # onset=100, buffer=20 callbacks → boundary = 120
        # Actually: the boundary is where to CUT the chunk. We want to
        # keep buffer_s of silence at the END of the chunk (padding).
        # So cut at onset + buffer_in_callbacks = 100 + 20 = 120.
        assert result == 120

    def test_no_trigger_below_min_chunk(self):
        det = self._make_detector(
            duration_s=0.5, callback_interval_s=0.01, min_chunk_s=5.0
        )
        # Plenty of silence but only 2s accumulated
        for i in range(100):
            result = det.feed(level=0.0, chunk_index=i, accumulated_s=2.0)
        assert result is None

    def test_triggers_when_min_chunk_met(self):
        det = self._make_detector(
            duration_s=0.5,
            callback_interval_s=0.01,
            min_chunk_s=3.0,
            buffer_s=0.0,
        )
        for i in range(50):
            result = det.feed(level=0.0, chunk_index=i, accumulated_s=5.0)
        assert result is not None

    def test_no_retrigger_on_same_silence(self):
        det = self._make_detector(
            duration_s=0.5, callback_interval_s=0.01, buffer_s=0.0
        )
        triggered_count = 0
        for i in range(200):
            result = det.feed(level=0.0, chunk_index=i, accumulated_s=10.0)
            if result is not None:
                triggered_count += 1
        assert triggered_count == 1

    def test_retriggers_after_speech_resumes(self):
        det = self._make_detector(
            duration_s=0.5, callback_interval_s=0.01, buffer_s=0.0
        )
        triggers = []
        # First silence gap
        for i in range(100):
            r = det.feed(level=0.0, chunk_index=i, accumulated_s=10.0)
            if r is not None:
                triggers.append(r)
        # Speech resumes
        for i in range(100, 200):
            det.feed(level=0.5, chunk_index=i, accumulated_s=20.0)
        # Second silence gap
        for i in range(200, 300):
            r = det.feed(level=0.0, chunk_index=i, accumulated_s=30.0)
            if r is not None:
                triggers.append(r)
        assert len(triggers) == 2

    def test_reset_clears_state(self):
        det = self._make_detector(
            duration_s=0.5, callback_interval_s=0.01, buffer_s=0.0
        )
        # Partial silence (not enough to trigger)
        for i in range(30):
            det.feed(level=0.0, chunk_index=i, accumulated_s=10.0)
        det.reset()
        # After reset, need full duration again
        for i in range(30, 60):
            result = det.feed(level=0.0, chunk_index=i, accumulated_s=10.0)
        assert result is None  # only 30 callbacks, not 50

    def test_threshold_boundary_exact(self):
        det = self._make_detector(threshold=0.02)
        # Level exactly at threshold is NOT silent
        det.feed(level=0.02, chunk_index=0, accumulated_s=10.0)
        assert det._consecutive_silent == 0
        # Level just below threshold IS silent
        det.feed(level=0.019, chunk_index=1, accumulated_s=10.0)
        assert det._consecutive_silent == 1

    def test_speech_resets_consecutive_count(self):
        det = self._make_detector(duration_s=1.0, callback_interval_s=0.01)
        # 50 silent callbacks
        for i in range(50):
            det.feed(level=0.0, chunk_index=i, accumulated_s=10.0)
        assert det._consecutive_silent == 50
        # One speech callback resets
        det.feed(level=0.5, chunk_index=50, accumulated_s=10.0)
        assert det._consecutive_silent == 0


class TestChunkManager:
    """Tests for background chunked transcription."""

    def _make_chunks(self, *durations_samples):
        """Create list of numpy audio chunks with given sample counts.

        Uses peak=2000 which maps to level=0.24 (above silence threshold).
        """
        return [np.full((n, 1), 2000, dtype=np.int16) for n in durations_samples]

    def test_bind_chunks(self):
        mgr = ChunkManager(model_size="tiny")
        chunks = self._make_chunks(100, 200)
        mgr.bind_chunks(chunks)
        assert mgr._chunks_ref is chunks

    def test_flush_enqueues_audio(self):
        mgr = ChunkManager(model_size="tiny")
        chunks = self._make_chunks(8000, 8000, 8000)
        mgr.bind_chunks(chunks)
        result = mgr.flush()
        assert result is True
        assert mgr._queue.qsize() == 1
        # Boundary moved
        assert mgr.boundary == 3

    def test_flush_no_new_audio_is_noop(self):
        mgr = ChunkManager(model_size="tiny")
        chunks = self._make_chunks(16000)
        mgr.bind_chunks(chunks)
        mgr.flush()
        # Second flush with no new chunks
        result = mgr.flush()
        assert result is False
        assert mgr._queue.qsize() == 1  # still just the first

    def test_flush_with_boundary(self):
        mgr = ChunkManager(model_size="tiny")
        chunks = self._make_chunks(8000, 8000, 8000, 8000)
        mgr.bind_chunks(chunks)
        # Flush only first 2 chunks
        mgr.flush(boundary=2)
        assert mgr.boundary == 2
        assert mgr._queue.qsize() == 1
        # Flush remaining
        mgr.flush()
        assert mgr.boundary == 4
        assert mgr._queue.qsize() == 2

    def test_flush_boundary_clamped_to_length(self):
        mgr = ChunkManager(model_size="tiny")
        chunks = self._make_chunks(8000, 8000)
        mgr.bind_chunks(chunks)
        mgr.flush(boundary=999)
        assert mgr.boundary == 2  # clamped to len(chunks)

    def test_worker_transcribes_and_stores(self):
        mgr = ChunkManager(model_size="tiny")
        chunks = self._make_chunks(16000)
        mgr.bind_chunks(chunks)

        with patch("chunks.transcribe_audio", return_value="hello world"):
            mgr.start_worker()
            mgr.flush()
            mgr.finish(timeout=5)

        assert mgr.get_transcript() == "hello world"

    def test_worker_multiple_chunks(self):
        mgr = ChunkManager(model_size="tiny")
        chunks = self._make_chunks(16000, 16000, 16000)
        mgr.bind_chunks(chunks)

        call_count = [0]

        def fake_transcribe(audio_data, *, model_size="small", progress_callback=None):
            call_count[0] += 1
            return f"chunk{call_count[0]}"

        with patch("chunks.transcribe_audio", side_effect=fake_transcribe):
            mgr.start_worker()
            mgr.flush(boundary=1)
            mgr.flush(boundary=2)
            mgr.flush()
            mgr.finish(timeout=5)

        assert mgr.get_transcript() == "chunk1 chunk2 chunk3"

    def test_worker_skips_empty_transcripts(self):
        mgr = ChunkManager(model_size="tiny")
        chunks = self._make_chunks(16000, 16000)
        mgr.bind_chunks(chunks)

        results = iter(["", "hello"])

        with patch(
            "chunks.transcribe_audio", side_effect=lambda *a, **k: next(results)
        ):
            mgr.start_worker()
            mgr.flush(boundary=1)
            mgr.flush()
            mgr.finish(timeout=5)

        assert mgr.get_transcript() == "hello"

    def test_worker_error_logged_and_continues(self):
        mgr = ChunkManager(model_size="tiny")
        chunks = self._make_chunks(16000, 16000)
        mgr.bind_chunks(chunks)

        call_count = [0]

        def fail_then_succeed(
            audio_data, *, model_size="small", progress_callback=None
        ):
            call_count[0] += 1
            if call_count[0] == 1:
                raise RuntimeError("model exploded")
            return "recovered"

        with patch("chunks.transcribe_audio", side_effect=fail_then_succeed):
            mgr.start_worker()
            mgr.flush(boundary=1)
            mgr.flush()
            mgr.finish(timeout=5)

        assert mgr.get_transcript() == "recovered"
        assert len(mgr._errors) == 1

    def test_stream_callback_called(self):
        mgr = ChunkManager(model_size="tiny")
        chunks = self._make_chunks(16000)
        mgr.bind_chunks(chunks)

        streamed = []
        mgr.set_stream_callback(streamed.append)

        with patch("chunks.transcribe_audio", return_value="streamed text"):
            mgr.start_worker()
            mgr.flush()
            mgr.finish(timeout=5)

        assert streamed == ["streamed text"]

    def test_stream_callback_not_called_for_empty(self):
        mgr = ChunkManager(model_size="tiny")
        chunks = self._make_chunks(16000)
        mgr.bind_chunks(chunks)

        streamed = []
        mgr.set_stream_callback(streamed.append)

        with patch("chunks.transcribe_audio", return_value=""):
            mgr.start_worker()
            mgr.flush()
            mgr.finish(timeout=5)

        assert streamed == []

    def test_progress_fraction_all_transcribed(self):
        mgr = ChunkManager(model_size="tiny", sample_rate=16000)
        chunks = self._make_chunks(16000, 16000)  # 2 chunks, 1s each
        mgr.bind_chunks(chunks)

        with patch("chunks.transcribe_audio", return_value="text"):
            mgr.start_worker()
            mgr.flush()  # flush all
            mgr.finish(timeout=5)

        # All 32000 samples transcribed out of 32000 recorded
        assert mgr.progress_fraction() == 1.0

    def test_progress_fraction_partial_flush(self):
        import threading as th

        mgr = ChunkManager(model_size="tiny", sample_rate=16000)
        chunks = self._make_chunks(16000, 16000)
        mgr.bind_chunks(chunks)

        chunk_processed = th.Event()

        def mock_transcribe(audio_data, *, model_size="small", progress_callback=None):
            chunk_processed.set()
            return "text"

        with patch("chunks.transcribe_audio", side_effect=mock_transcribe):
            mgr.start_worker()
            mgr.flush(boundary=1)  # flush only first chunk
            chunk_processed.wait(timeout=5)

        # 16000 transcribed out of 32000 recorded = 0.5
        assert mgr.progress_fraction() == 0.5

    def test_progress_fraction_nothing_transcribed(self):
        mgr = ChunkManager(model_size="tiny", sample_rate=16000)
        chunks = self._make_chunks(16000, 16000)
        mgr.bind_chunks(chunks)
        # Flush but don't start worker — nothing transcribed
        mgr.flush()
        assert mgr.progress_fraction() == 0.0

    def test_is_done(self):
        mgr = ChunkManager(model_size="tiny")
        chunks = self._make_chunks(16000)
        mgr.bind_chunks(chunks)

        with patch("chunks.transcribe_audio", return_value="done"):
            mgr.start_worker()
            mgr.flush()
            mgr.finish(timeout=5)

        assert mgr.is_done() is True

    def test_finish_without_start_is_safe(self):
        mgr = ChunkManager(model_size="tiny")
        chunks = self._make_chunks(16000)
        mgr.bind_chunks(chunks)
        # finish without starting worker — should not raise
        mgr.finish(timeout=1)
        assert mgr.get_transcript() == ""


class TestTrimSilence:
    """Tests for trim_silence()."""

    def _make_audio(self, *segments):
        """Build audio from (level, duration_samples) pairs.

        level=0.0 produces silence, level>0 produces samples at that peak.
        """
        parts = []
        for level, n_samples in segments:
            if level == 0.0:
                parts.append(np.zeros((n_samples, 1), dtype=np.int16))
            else:
                peak = int(level / 4.0 * 32768)
                parts.append(np.full((n_samples, 1), peak, dtype=np.int16))
        return np.concatenate(parts, axis=0)

    def test_all_silence_returns_none(self):
        audio = self._make_audio((0.0, 16000))
        assert trim_silence(audio) is None

    def test_speech_only_unchanged(self):
        audio = self._make_audio((0.5, 16000))
        result = trim_silence(audio, buffer_s=0.0)
        assert result is not None
        assert len(result) == len(audio)

    def test_trims_leading_silence(self):
        # 1s silence + 1s speech
        audio = self._make_audio((0.0, 16000), (0.5, 16000))
        result = trim_silence(audio, buffer_s=0.0)
        assert result is not None
        assert len(result) < len(audio)
        # Should start near the speech, not at the beginning
        assert len(result) <= 16400  # speech + some block alignment

    def test_trims_trailing_silence(self):
        # 1s speech + 1s silence
        audio = self._make_audio((0.5, 16000), (0.0, 16000))
        result = trim_silence(audio, buffer_s=0.0)
        assert result is not None
        assert len(result) < len(audio)
        assert len(result) <= 16400

    def test_trims_both_ends(self):
        # 1s silence + 1s speech + 1s silence
        audio = self._make_audio((0.0, 16000), (0.5, 16000), (0.0, 16000))
        result = trim_silence(audio, buffer_s=0.0)
        assert result is not None
        assert len(result) < 20000  # much less than 48000

    def test_buffer_preserves_padding(self):
        # 2s silence + 1s speech + 2s silence
        audio = self._make_audio((0.0, 32000), (0.5, 16000), (0.0, 32000))
        result = trim_silence(audio, buffer_s=0.5)
        assert result is not None
        # Should be speech (16000) + 2x buffer (2x8000) = ~32000, plus block alignment
        assert len(result) > 16000
        assert len(result) < len(audio)
