# Generated By: Claude Code (Claude Opus 4.6)
"""Chunked transcription support — SilenceDetector and ChunkManager.

SilenceDetector tracks audio levels to find natural chunk boundaries.
ChunkManager coordinates background transcription of audio chunks.
"""

import logging
import math

log = logging.getLogger(__name__)


class SilenceDetector:
    """Detects silence gaps in an audio stream for chunk boundary selection.

    Tracks consecutive silent callbacks and fires once when silence exceeds
    a duration threshold. The returned chunk index marks where to cut,
    adjusted by a buffer to avoid clipping speech.

    Args:
        threshold: Audio level (0.0-1.0) below which is considered silence.
        duration_s: Seconds of continuous silence required to trigger.
        min_chunk_s: Minimum accumulated audio before triggering.
        buffer_s: Silence padding kept at the end of a chunk cut.
        callback_interval_s: Approximate time between audio callbacks.
    """

    def __init__(
        self,
        threshold: float = 0.02,
        duration_s: float = 1.5,
        min_chunk_s: float = 3.0,
        buffer_s: float = 0.5,
        callback_interval_s: float = 0.01,
    ):
        self._threshold = threshold
        self._duration_s = duration_s
        self._min_chunk_s = min_chunk_s
        self._buffer_callbacks = max(0, math.floor(buffer_s / callback_interval_s))
        self._min_silent_callbacks = math.ceil(duration_s / callback_interval_s)
        self._consecutive_silent = 0
        self._silence_onset_idx: int | None = None
        self._triggered = False

    def feed(self, level: float, chunk_index: int, accumulated_s: float) -> int | None:
        """Feed an audio level sample.

        Args:
            level: Current audio level (0.0-1.0).
            chunk_index: Index into the chunks list for this callback.
            accumulated_s: Total audio accumulated since last flush.

        Returns:
            Chunk index to use as the cut boundary, or None if no trigger.
            The boundary includes buffer_s of silence padding.
        """
        if level < self._threshold:
            if self._consecutive_silent == 0:
                self._silence_onset_idx = chunk_index
            self._consecutive_silent += 1

            if (
                not self._triggered
                and self._consecutive_silent >= self._min_silent_callbacks
                and accumulated_s >= self._min_chunk_s
                and self._silence_onset_idx is not None
            ):
                self._triggered = True
                boundary = self._silence_onset_idx + self._buffer_callbacks
                return boundary
        else:
            self._consecutive_silent = 0
            self._silence_onset_idx = None
            self._triggered = False

        return None

    def reset(self) -> None:
        """Clear all state. Call when resuming from pause."""
        self._consecutive_silent = 0
        self._silence_onset_idx = None
        self._triggered = False
