# Generated By: Claude Code (Claude Opus 4.6)
"""Chunked transcription support — SilenceDetector and ChunkManager.

SilenceDetector tracks audio levels to find natural chunk boundaries.
ChunkManager coordinates background transcription of audio chunks.
"""

import logging
import math
import queue
import threading
from typing import Callable

import numpy as np

from whisper import transcribe_audio

log = logging.getLogger(__name__)


class SilenceDetector:
    """Detects silence gaps in an audio stream for chunk boundary selection.

    Tracks consecutive silent callbacks and fires once when silence exceeds
    a duration threshold. The returned chunk index marks where to cut,
    adjusted by a buffer to avoid clipping speech.

    Args:
        threshold: Audio level (0.0-1.0) below which is considered silence.
        duration_s: Seconds of continuous silence required to trigger.
        min_chunk_s: Minimum accumulated audio before triggering.
        buffer_s: Silence padding kept at the end of a chunk cut.
        callback_interval_s: Approximate time between audio callbacks.
    """

    def __init__(
        self,
        threshold: float = 0.02,
        duration_s: float = 1.5,
        min_chunk_s: float = 3.0,
        buffer_s: float = 0.5,
        callback_interval_s: float = 0.01,
    ):
        self._threshold = threshold
        self._duration_s = duration_s
        self._min_chunk_s = min_chunk_s
        self._buffer_callbacks = max(0, math.floor(buffer_s / callback_interval_s))
        self._min_silent_callbacks = math.ceil(duration_s / callback_interval_s)
        self._consecutive_silent = 0
        self._silence_onset_idx: int | None = None
        self._triggered = False

    def feed(self, level: float, chunk_index: int, accumulated_s: float) -> int | None:
        """Feed an audio level sample.

        Args:
            level: Current audio level (0.0-1.0).
            chunk_index: Index into the chunks list for this callback.
            accumulated_s: Total audio accumulated since last flush.

        Returns:
            Chunk index to use as the cut boundary, or None if no trigger.
            The boundary includes buffer_s of silence padding.
        """
        if level < self._threshold:
            if self._consecutive_silent == 0:
                self._silence_onset_idx = chunk_index
            self._consecutive_silent += 1

            if (
                not self._triggered
                and self._consecutive_silent >= self._min_silent_callbacks
                and accumulated_s >= self._min_chunk_s
                and self._silence_onset_idx is not None
            ):
                self._triggered = True
                boundary = self._silence_onset_idx + self._buffer_callbacks
                return boundary
        else:
            self._consecutive_silent = 0
            self._silence_onset_idx = None
            self._triggered = False

        return None

    def reset(self) -> None:
        """Clear all state. Call when resuming from pause."""
        self._consecutive_silent = 0
        self._silence_onset_idx = None
        self._triggered = False


class ChunkManager:
    """Coordinates background transcription of audio chunks.

    Tracks which audio has been sent for transcription vs. still accumulating.
    A single worker thread processes chunks sequentially from a queue,
    reusing the Whisper model across calls.

    Args:
        model_size: Whisper model size for transcription.
        sample_rate: Audio sample rate (for progress calculation).
    """

    def __init__(self, model_size: str = "small", sample_rate: int = 16000):
        self._model_size = model_size
        self._sample_rate = sample_rate
        self._chunks_ref: list[np.ndarray] | None = None
        self._boundary: int = 0
        self._queue: queue.Queue[np.ndarray | None] = queue.Queue()
        self._transcripts: list[str] = []
        self._errors: list[Exception] = []
        self._stream_callback: Callable[[str], None] | None = None
        self._total_samples_sent: int = 0
        self._total_samples_done: int = 0
        self._worker: threading.Thread | None = None
        self._finished = threading.Event()

    def bind_chunks(self, chunks: list[np.ndarray]) -> None:
        """Bind to the recording's chunks list."""
        self._chunks_ref = chunks

    def set_stream_callback(self, callback: Callable[[str], None]) -> None:
        """Set callback for streaming transcripts as they complete."""
        self._stream_callback = callback

    def start_worker(self) -> None:
        """Start the background transcription thread."""
        self._worker = threading.Thread(target=self._worker_loop, daemon=True)
        self._worker.start()

    def flush(self, boundary: int | None = None) -> bool:
        """Enqueue audio from current boundary to the given index.

        Args:
            boundary: Chunk index to flush up to. If None, flush all.

        Returns:
            True if audio was enqueued, False if nothing new.
        """
        if self._chunks_ref is None:
            return False

        end = len(self._chunks_ref) if boundary is None else boundary
        end = min(end, len(self._chunks_ref))

        if end <= self._boundary:
            return False

        audio = np.concatenate(self._chunks_ref[self._boundary : end], axis=0)
        self._boundary = end
        self._total_samples_sent += len(audio)
        self._queue.put(audio)
        return True

    def finish(self, timeout: float = 30.0) -> None:
        """Flush remaining audio, signal worker to stop, and wait."""
        self.flush()
        if self._worker is not None:
            self._queue.put(None)  # sentinel
            self._worker.join(timeout=timeout)
        self._finished.set()

    def get_transcript(self) -> str:
        """Join all completed transcripts."""
        return " ".join(t for t in self._transcripts if t).strip()

    def progress_fraction(self) -> float:
        """Fraction of sent audio that has been transcribed (0.0-1.0)."""
        if self._total_samples_sent == 0:
            return 0.0
        return self._total_samples_done / self._total_samples_sent

    def is_done(self) -> bool:
        """True when worker has finished processing all chunks."""
        return self._finished.is_set()

    def _worker_loop(self) -> None:
        """Process chunks from the queue until sentinel."""
        while True:
            item = self._queue.get()
            if item is None:
                break
            try:
                text = transcribe_audio(item, model_size=self._model_size)
                if text:
                    self._transcripts.append(text)
                    if self._stream_callback:
                        self._stream_callback(text)
                self._total_samples_done += len(item)
            except Exception as e:
                log.error("Chunk transcription failed: %s", e)
                self._errors.append(e)
                self._total_samples_done += len(item)
