#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""
Voice-to-text for Claude Code CLI.
Records audio from microphone, transcribes locally with faster-whisper.
Cross-platform: Linux (Fedora) and Windows 11.

A tkinter popup shows recording status with elapsed time and cwd context.
Supports pause/resume, input device selection, and stop to end recording.

Usage:
    python3 voice.py [--model tiny|base|small] [--device DEVICE_ID]
    Transcript is printed to stdout.
"""

import argparse
import os
import sys
import tempfile
import time
import uuid
import wave

try:
    import tkinter as tk
    from tkinter import ttk
except ModuleNotFoundError:
    print(
        "Error: tkinter not found. Install it with:\n"
        "  Fedora: sudo dnf install python3-tkinter\n"
        "  Ubuntu/Debian: sudo apt install python3-tk\n"
        "  Windows/macOS: tkinter is included with standard Python",
        file=sys.stderr,
    )
    sys.exit(1)

import numpy as np
import sounddevice as sd
from faster_whisper import WhisperModel

SAMPLE_RATE = 16000
MAX_PATH_DISPLAY_LENGTH = 60
TIMER_UPDATE_MS = 200


class RecordingError(Exception):
    """Raised when audio recording fails."""


def _truncate_path(path: str, *, max_length: int = MAX_PATH_DISPLAY_LENGTH) -> str:
    if len(path) > max_length:
        return "..." + path[-(max_length - 3) :]
    return path


def _get_input_devices() -> list[dict]:
    devices = sd.query_devices()
    result = []
    for i, dev in enumerate(devices):
        if dev["max_input_channels"] > 0:
            result.append({"id": i, "name": dev["name"]})
    return result


def record_with_gui(cwd: str, *, device_id: int | None = None) -> np.ndarray:
    """Show a tkinter popup while recording. Returns audio data.

    Raises:
        RecordingError: If no audio was captured.
    """
    chunks: list[np.ndarray] = []
    recording = True
    paused = False
    start_time = time.time()
    paused_elapsed = 0.0
    pause_start = 0.0

    def audio_callback(indata, _frames, _time_info, _status):
        if recording and not paused:
            chunks.append(indata.copy())

    stream_kwargs: dict = {
        "samplerate": SAMPLE_RATE,
        "channels": 1,
        "dtype": "int16",
        "callback": audio_callback,
    }
    if device_id is not None:
        stream_kwargs["device"] = device_id

    try:
        stream = sd.InputStream(**stream_kwargs)
    except Exception as e:
        print(f"Failed to access microphone: {e}", file=sys.stderr)
        sys.exit(1)

    root = tk.Tk()
    root.title("Claude Voice")
    root.attributes("-topmost", True)
    root.resizable(False, False)

    frame = tk.Frame(root, padx=20, pady=15)
    frame.pack()

    status_var = tk.StringVar(value="Recording...")
    status_label = tk.Label(
        frame,
        textvariable=status_var,
        font=("sans-serif", 16, "bold"),
        fg="#cc0000",
    )
    status_label.pack()

    elapsed_var = tk.StringVar(value="0:00")
    tk.Label(frame, textvariable=elapsed_var, font=("monospace", 24)).pack(
        pady=(10, 5)
    )

    display_cwd = _truncate_path(cwd)
    tk.Label(frame, text=display_cwd, font=("monospace", 9), fg="#666666").pack(
        pady=(0, 10)
    )

    # Input device selector
    input_devices = _get_input_devices()
    if len(input_devices) > 1:
        device_frame = tk.Frame(frame)
        device_frame.pack(pady=(0, 10))
        tk.Label(device_frame, text="Input:", font=("sans-serif", 9)).pack(side=tk.LEFT)
        device_names = [d["name"] for d in input_devices]
        device_combo = ttk.Combobox(
            device_frame,
            values=device_names,
            state="readonly",
            width=30,
        )
        # Select current device
        current_idx = 0
        if device_id is not None:
            for i, d in enumerate(input_devices):
                if d["id"] == device_id:
                    current_idx = i
                    break
        device_combo.current(current_idx)
        device_combo.pack(side=tk.LEFT, padx=(5, 0))

        def on_device_change(_event):
            nonlocal stream, device_id
            selected_idx = device_combo.current()
            new_device_id = input_devices[selected_idx]["id"]
            if new_device_id == device_id:
                return
            device_id = new_device_id
            stream.stop()
            stream.close()
            try:
                stream = sd.InputStream(
                    samplerate=SAMPLE_RATE,
                    channels=1,
                    dtype="int16",
                    callback=audio_callback,
                    device=device_id,
                )
                stream.start()
            except Exception as e:
                status_var.set(f"Device error: {e}")

        device_combo.bind("<<ComboboxSelected>>", on_device_change)

    button_frame = tk.Frame(frame)
    button_frame.pack()

    def toggle_pause():
        nonlocal paused, pause_start, paused_elapsed
        if paused:
            paused_elapsed += time.time() - pause_start
            paused = False
            status_var.set("Recording...")
            status_label.config(fg="#cc0000")
            pause_btn.config(text="Pause")
            update_timer()
        else:
            pause_start = time.time()
            paused = True
            status_var.set("Paused")
            status_label.config(fg="#cc8800")
            pause_btn.config(text="Resume")

    pause_btn = tk.Button(
        button_frame,
        text="Pause",
        font=("sans-serif", 12),
        command=toggle_pause,
        bg="#cc8800",
        fg="white",
        activebackground="#996600",
        activeforeground="white",
        padx=15,
        pady=5,
    )
    pause_btn.pack(side=tk.LEFT, padx=(0, 5))

    def stop_recording():
        nonlocal recording
        recording = False
        root.destroy()

    stop_btn = tk.Button(
        button_frame,
        text="Stop",
        font=("sans-serif", 12),
        command=stop_recording,
        bg="#cc0000",
        fg="white",
        activebackground="#990000",
        activeforeground="white",
        padx=15,
        pady=5,
    )
    stop_btn.pack(side=tk.LEFT)

    def update_timer():
        if recording and not paused:
            elapsed = int(time.time() - start_time - paused_elapsed)
            mins, secs = divmod(elapsed, 60)
            elapsed_var.set(f"{mins}:{secs:02d}")
            root.after(TIMER_UPDATE_MS, update_timer)

    root.protocol("WM_DELETE_WINDOW", stop_recording)

    try:
        stream.start()
        update_timer()
        root.mainloop()
    finally:
        stream.stop()
        stream.close()

    if not chunks:
        raise RecordingError("No audio captured.")

    audio_data = np.concatenate(chunks, axis=0)
    duration = len(audio_data) / SAMPLE_RATE
    print(f"Captured {duration:.1f}s of audio.", file=sys.stderr)
    return audio_data


def save_wav(audio_data: np.ndarray) -> str:
    """Save audio to a temporary WAV file."""
    file_id = uuid.uuid4().hex[:8]
    wav_path = os.path.join(tempfile.gettempdir(), f"claude_voice_{file_id}.wav")
    with wave.open(wav_path, "wb") as wf:
        wf.setnchannels(1)
        wf.setsampwidth(2)
        wf.setframerate(SAMPLE_RATE)
        wf.writeframes(audio_data.tobytes())
    return wav_path


def transcribe(wav_path: str, *, model_size: str = "base") -> str:
    """Transcribe WAV file using faster-whisper."""
    print(f"Transcribing with model '{model_size}'...", file=sys.stderr)
    try:
        model = WhisperModel(model_size, device="cpu", compute_type="int8")
    except Exception as e:
        print(
            f"Failed to load Whisper model '{model_size}': {e}\n"
            "Ensure faster-whisper is installed and you have internet "
            "connectivity for initial model download.",
            file=sys.stderr,
        )
        raise
    segments, _ = model.transcribe(wav_path, beam_size=5)
    text_parts = [seg.text.strip() for seg in segments]
    return " ".join(text_parts).strip()


def main() -> None:
    parser = argparse.ArgumentParser(description="Voice-to-text for Claude Code CLI")
    parser.add_argument(
        "--model",
        type=str,
        default="base",
        choices=["tiny", "base", "small"],
        help="Whisper model size (default: base)",
    )
    parser.add_argument(
        "--device",
        type=int,
        default=None,
        help="Audio input device ID (use --list-devices to see available devices)",
    )
    parser.add_argument(
        "--list-devices",
        action="store_true",
        help="List available audio input devices and exit",
    )
    args = parser.parse_args()

    if args.list_devices:
        devices = _get_input_devices()
        if not devices:
            print("No input devices found.", file=sys.stderr)
            sys.exit(1)
        for dev in devices:
            print(f"  {dev['id']}: {dev['name']}", file=sys.stderr)
        sys.exit(0)

    cwd = os.getcwd()
    try:
        audio_data = record_with_gui(cwd, device_id=args.device)
    except RecordingError as e:
        print(str(e), file=sys.stderr)
        sys.exit(1)

    wav_path = None
    try:
        wav_path = save_wav(audio_data)
        transcript = transcribe(wav_path, model_size=args.model)
    finally:
        if wav_path and os.path.exists(wav_path):
            os.remove(wav_path)

    if not transcript:
        print("No speech detected in audio.", file=sys.stderr)
        sys.exit(1)

    # stdout = transcript (what Claude Code reads)
    print(transcript)


if __name__ == "__main__":
    main()
