#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""
Voice-to-text for Claude Code CLI.
Records audio from microphone, transcribes locally with faster-whisper.
Cross-platform: Linux (Fedora) and Windows 11.

A tkinter popup shows recording status with elapsed time and cwd context.
Supports pause/resume and cancel/done controls.

Usage:
    python3 voice.py [--model tiny|base|small] [--device DEVICE_ID]
    Transcript is printed to stdout.
"""

import argparse
import json
import logging
import os
import sys
import tempfile
import time
import uuid
import wave

try:
    import tkinter as tk
except ModuleNotFoundError:
    print(
        "Error: tkinter not found. Install it with:\n"
        "  Fedora: sudo dnf install python3-tkinter\n"
        "  Ubuntu/Debian: sudo apt install python3-tk\n"
        "  Windows/macOS: tkinter is included with standard Python",
        file=sys.stderr,
    )
    sys.exit(1)

import numpy as np
import sounddevice as sd
from faster_whisper import WhisperModel

log = logging.getLogger(__name__)

APP_NAME = "claude-skill-voice"
CONFIG_FILENAME = "settings.json"
LOCK_FILENAME = "voice.lock"
CONFIG_KEY_WINDOW_X = "window_x"
CONFIG_KEY_WINDOW_Y = "window_y"
CONFIG_KEY_TRANSCRIBE_RATIO = "transcribe_ratio"

SAMPLE_RATE = 16000
AUDIO_CHANNELS = 1
AUDIO_DTYPE = "int16"
AUDIO_SAMPLE_WIDTH = 2
DEFAULT_MODEL_SIZE = "base"
WHISPER_BEAM_SIZE = 5
WHISPER_DEVICE = "cpu"
WHISPER_COMPUTE_TYPE = "int8"

EXIT_SUCCESS = 0
EXIT_ERROR = 1

MAX_PATH_DISPLAY_LENGTH = 60
TIMER_UPDATE_MS = 200

COLOR_RECORDING = "#cc0000"
COLOR_RECORDING_ACTIVE = "#990000"
COLOR_PAUSED = "#cc8800"
COLOR_PAUSED_ACTIVE = "#996600"
COLOR_DONE = "#228B22"
COLOR_DONE_ACTIVE = "#1a6b1a"
COLOR_MUTED = "#666666"

FONT_STATUS = ("sans-serif", 16, "bold")
FONT_TIMER = ("monospace", 24)
FONT_DETAIL = ("monospace", 9)
FONT_BUTTON = ("sans-serif", 12)


class RecordingError(Exception):
    """Raised when audio recording fails."""


class RecordingCancelled(Exception):
    """Raised when the user cancels recording."""


class LockAcquireError(Exception):
    """Raised when the lock file cannot be acquired."""


def _config_path() -> str:
    """Return the path to the settings JSON file, platform-appropriate."""
    if sys.platform == "win32":
        base = os.environ.get("APPDATA", os.path.expanduser("~"))
    else:
        base = os.environ.get(
            "XDG_CONFIG_HOME", os.path.join(os.path.expanduser("~"), ".config")
        )
    return os.path.join(base, APP_NAME, CONFIG_FILENAME)


class Config:
    """Persistent settings backed by a JSON file."""

    def __init__(self, path: str | None = None):
        self._path = path or _config_path()
        self._data: dict = {}
        self._load()

    def _load(self) -> None:
        if not os.path.exists(self._path):
            return
        try:
            with open(self._path) as f:
                self._data = json.load(f)
        except (json.JSONDecodeError, OSError):
            self._data = {}

    def save(self) -> None:
        os.makedirs(os.path.dirname(self._path), exist_ok=True)
        tmp = self._path + ".tmp"
        with open(tmp, "w") as f:
            json.dump(self._data, f, indent=2)
        os.replace(tmp, self._path)

    @property
    def window_x(self) -> int | None:
        raw = self._data.get(CONFIG_KEY_WINDOW_X)
        return int(raw) if isinstance(raw, (int, float)) else None

    @window_x.setter
    def window_x(self, value: int) -> None:
        self._data[CONFIG_KEY_WINDOW_X] = value

    @property
    def window_y(self) -> int | None:
        raw = self._data.get(CONFIG_KEY_WINDOW_Y)
        return int(raw) if isinstance(raw, (int, float)) else None

    @window_y.setter
    def window_y(self, value: int) -> None:
        self._data[CONFIG_KEY_WINDOW_Y] = value

    @property
    def transcribe_ratio(self) -> float | None:
        raw = self._data.get(CONFIG_KEY_TRANSCRIBE_RATIO)
        if isinstance(raw, (int, float)) and raw > 0:
            return float(raw)
        return None

    @transcribe_ratio.setter
    def transcribe_ratio(self, value: float) -> None:
        self._data[CONFIG_KEY_TRANSCRIBE_RATIO] = round(value, 4)


def _lock_path() -> str:
    """Return path to the PID lockfile."""
    config_dir = os.path.dirname(_config_path())
    return os.path.join(config_dir, LOCK_FILENAME)


def _is_pid_alive(pid: int) -> bool:
    """Check if a process with the given PID is running."""
    try:
        os.kill(pid, 0)  # signal 0: check existence, does not kill
        return True
    except PermissionError:
        return True  # exists but we lack permission to signal it
    except OSError:
        return False


def _read_lock_pid() -> int | None:
    """Read and return the PID from the lockfile, or None if unreadable."""
    path = _lock_path()
    if not os.path.exists(path):
        return None
    try:
        with open(path) as f:
            return int(f.read().strip())
    except (ValueError, OSError):
        return None


def _write_lock_file(path: str, pid: int) -> None:
    """Atomically create lockfile with PID. Raises FileExistsError if exists."""
    fd = None
    try:
        fd = os.open(path, os.O_CREAT | os.O_EXCL | os.O_WRONLY)
        os.write(fd, str(pid).encode())
    finally:
        if fd is not None:
            os.close(fd)


def _acquire_lock() -> None:
    """Acquire the PID lockfile. Raises LockAcquireError if held by another.

    Uses O_CREAT|O_EXCL for atomic file creation to prevent race conditions.
    """
    path = _lock_path()
    my_pid = os.getpid()
    os.makedirs(os.path.dirname(path), exist_ok=True)

    # Fast path: try atomic create
    try:
        _write_lock_file(path, my_pid)
        log.debug("lock acquired: pid=%d", my_pid)
        return
    except FileExistsError:
        pass

    # Lock file exists — check who owns it
    lock_pid = _read_lock_pid()

    if lock_pid is not None and lock_pid == my_pid:
        log.debug("lock already owned by us: pid=%d", my_pid)
        return

    if lock_pid is not None and _is_pid_alive(lock_pid):
        log.debug("lock held by live process: pid=%d", lock_pid)
        raise LockAcquireError(
            "Another voice recording session is already running. "
            "Finish that session before starting a new one."
        )

    # Stale lock (process dead or bad PID) — remove and retry
    log.debug("removing stale lock: pid=%s", lock_pid)
    try:
        os.remove(path)
    except OSError:
        pass
    try:
        _write_lock_file(path, my_pid)
        log.debug("lock acquired after stale cleanup: pid=%d", my_pid)
    except FileExistsError:
        raise LockAcquireError(
            "Failed to acquire lock. Another session may have started."
        )


def _release_lock() -> None:
    """Remove the PID lockfile only if we own it."""
    lock_pid = _read_lock_pid()
    if lock_pid is not None and lock_pid != os.getpid():
        log.warning(
            "lock not owned by us (owner=%d, self=%d), not releasing",
            lock_pid,
            os.getpid(),
        )
        return
    try:
        os.remove(_lock_path())
        log.debug("lock released")
    except OSError:
        pass


def _home_relative_path(path: str) -> str:
    """Convert an absolute path to ~/relative form."""
    home = os.path.expanduser("~")
    if path == home or path.startswith(home + os.sep):
        return "~" + path[len(home) :]
    return path


def _truncate_path(path: str, *, max_length: int = MAX_PATH_DISPLAY_LENGTH) -> str:
    if len(path) > max_length:
        return "..." + path[-(max_length - 3) :]
    return path


def _get_default_input_device() -> int:
    """Return the sounddevice index of the system default input device."""
    default = sd.default.device[0]
    if default is None or default < 0:
        devices = sd.query_devices()
        for i, dev in enumerate(devices):
            if dev["max_input_channels"] > 0:
                return i
        raise RecordingError("No input devices found.")
    return int(default)


def _get_input_devices() -> list[dict]:
    devices = sd.query_devices()
    result = []
    for i, dev in enumerate(devices):
        if dev["max_input_channels"] > 0:
            result.append({"id": i, "name": dev["name"]})
    return result


def record_with_gui(
    cwd: str, *, device_id: int | None = None, config: Config | None = None
) -> np.ndarray:
    """Show a tkinter popup while recording. Returns audio data.

    Raises:
        RecordingError: If no audio was captured.
        RecordingCancelled: If the user cancelled recording.
    """
    if config is None:
        config = Config()
    if device_id is None:
        device_id = _get_default_input_device()
        log.debug("resolved default input device: %d", device_id)

    chunks: list[np.ndarray] = []
    recording = True
    paused = False
    cancelled = False
    start_time = time.time()
    paused_elapsed = 0.0
    pause_start = 0.0

    callback_count = [0]

    def audio_callback(indata, _frames, _time_info, status):
        callback_count[0] += 1
        if status:
            log.warning("audio_callback status: %s", status)
        if recording and not paused:
            chunks.append(indata.copy())
            if callback_count[0] % 50 == 0:
                peak = int(np.max(np.abs(indata)))
                log.debug(
                    "callback #%d, chunks=%d, peak=%d",
                    callback_count[0],
                    len(chunks),
                    peak,
                )

    try:
        stream = sd.InputStream(
            samplerate=SAMPLE_RATE,
            channels=AUDIO_CHANNELS,
            dtype=AUDIO_DTYPE,
            callback=audio_callback,
            device=device_id,
        )
    except Exception as e:
        log.error("Failed to access microphone: %s", e)
        sys.exit(EXIT_ERROR)

    root = tk.Tk()
    root.title("Claude Voice")
    root.attributes("-topmost", True)
    root.resizable(False, False)

    if config.window_x is not None and config.window_y is not None:
        root.geometry(f"+{config.window_x}+{config.window_y}")

    frame = tk.Frame(root, padx=20, pady=15)
    frame.pack()

    timer_frame = tk.Frame(frame)
    timer_frame.pack(pady=(10, 5))
    timer_frame.grid_columnconfigure(0, minsize=160)

    status_var = tk.StringVar(value="Recording:")
    status_label = tk.Label(
        timer_frame,
        textvariable=status_var,
        font=FONT_STATUS,
        fg=COLOR_RECORDING,
        width=11,
        anchor="w",
    )
    status_label.grid(row=0, column=0, sticky="w", padx=(0, 5))

    elapsed_var = tk.StringVar(value="0:00")
    tk.Label(timer_frame, textvariable=elapsed_var, font=FONT_STATUS).grid(
        row=0, column=1, sticky="e"
    )

    tk.Label(timer_frame, text="Transcribe:", font=FONT_STATUS, fg=COLOR_MUTED).grid(
        row=1, column=0, sticky="w", padx=(0, 5)
    )
    transcribe_est_var = tk.StringVar(value="unknown")
    tk.Label(
        timer_frame,
        textvariable=transcribe_est_var,
        font=FONT_STATUS,
        fg=COLOR_MUTED,
    ).grid(row=1, column=1, sticky="e")

    display_cwd = _truncate_path(_home_relative_path(cwd))
    tk.Label(frame, text=display_cwd, font=FONT_DETAIL, fg=COLOR_MUTED).pack()

    device_name = sd.query_devices(device_id)["name"]
    tk.Label(frame, text=f"Mic: {device_name}", font=FONT_DETAIL, fg=COLOR_MUTED).pack(
        pady=(0, 10)
    )

    button_frame = tk.Frame(frame)
    button_frame.pack()

    def _save_pos_and_destroy():
        try:
            config.window_x = root.winfo_x()
            config.window_y = root.winfo_y()
            config.save()
        except Exception:
            pass
        root.destroy()

    def cancel_recording():
        nonlocal recording, cancelled
        recording = False
        cancelled = True
        _save_pos_and_destroy()

    def toggle_pause():
        nonlocal paused, pause_start, paused_elapsed
        if paused:
            paused_elapsed += time.time() - pause_start
            paused = False
            status_var.set("Recording:")
            status_label.config(fg=COLOR_RECORDING)
            pause_btn.config(text="Pause")
            update_timer()
        else:
            pause_start = time.time()
            paused = True
            status_var.set("Paused:")
            status_label.config(fg=COLOR_PAUSED)
            pause_btn.config(text="Resume")

    def done_recording():
        nonlocal recording
        recording = False
        _save_pos_and_destroy()

    btn_width = 7

    cancel_btn = tk.Button(
        button_frame,
        text="Cancel",
        font=FONT_BUTTON,
        command=cancel_recording,
        bg=COLOR_RECORDING,
        fg="white",
        activebackground=COLOR_RECORDING_ACTIVE,
        activeforeground="white",
        width=btn_width,
        pady=5,
    )
    cancel_btn.pack(side=tk.LEFT, padx=(0, 5))

    pause_btn = tk.Button(
        button_frame,
        text="Pause",
        font=FONT_BUTTON,
        command=toggle_pause,
        bg=COLOR_PAUSED,
        fg="white",
        activebackground=COLOR_PAUSED_ACTIVE,
        activeforeground="white",
        width=btn_width,
        pady=5,
    )
    pause_btn.pack(side=tk.LEFT, padx=(0, 5))

    done_btn = tk.Button(
        button_frame,
        text="Done",
        font=FONT_BUTTON,
        command=done_recording,
        bg=COLOR_DONE,
        fg="white",
        activebackground=COLOR_DONE_ACTIVE,
        activeforeground="white",
        width=btn_width,
        pady=5,
    )
    done_btn.pack(side=tk.LEFT)

    root.bind("<Escape>", lambda _e: cancel_recording())
    root.bind("<space>", lambda _e: toggle_pause())
    root.bind("<Return>", lambda _e: done_recording())

    saved_ratio = config.transcribe_ratio

    def update_timer():
        if recording and not paused:
            elapsed = int(time.time() - start_time - paused_elapsed)
            mins, secs = divmod(elapsed, 60)
            elapsed_var.set(f"{mins}:{secs:02d}")
            if saved_ratio is not None:
                est = int(elapsed * saved_ratio)
                est_mins, est_secs = divmod(est, 60)
                transcribe_est_var.set(f"{est_mins}:{est_secs:02d}")
            root.after(TIMER_UPDATE_MS, update_timer)

    root.protocol("WM_DELETE_WINDOW", cancel_recording)

    try:
        stream.start()
        update_timer()
        root.mainloop()
    finally:
        stream.stop()
        stream.close()

    log.debug(
        "recording ended: chunks=%d, callback_count=%d, cancelled=%s",
        len(chunks),
        callback_count[0],
        cancelled,
    )

    if cancelled:
        raise RecordingCancelled("Recording cancelled.")

    if not chunks:
        raise RecordingError("No audio captured.")

    audio_data = np.concatenate(chunks, axis=0)
    duration = len(audio_data) / SAMPLE_RATE
    log.info("Captured %.1fs of audio.", duration)
    return audio_data


def save_wav(audio_data: np.ndarray) -> str:
    """Save audio to a temporary WAV file."""
    file_id = uuid.uuid4().hex[:8]
    wav_path = os.path.join(tempfile.gettempdir(), f"claude_voice_{file_id}.wav")
    with wave.open(wav_path, "wb") as wf:
        wf.setnchannels(AUDIO_CHANNELS)
        wf.setsampwidth(AUDIO_SAMPLE_WIDTH)
        wf.setframerate(SAMPLE_RATE)
        wf.writeframes(audio_data.tobytes())
    return wav_path


def transcribe(wav_path: str, *, model_size: str = DEFAULT_MODEL_SIZE) -> str:
    """Transcribe WAV file using faster-whisper."""
    log.info("Transcribing with model '%s'...", model_size)
    # Suppress stdout from ctranslate2/faster-whisper progress output
    devnull = open(os.devnull, "w")  # noqa: SIM115
    saved_stdout = sys.stdout
    sys.stdout = devnull
    try:
        model = WhisperModel(
            model_size, device=WHISPER_DEVICE, compute_type=WHISPER_COMPUTE_TYPE
        )
        segments, _ = model.transcribe(wav_path, beam_size=WHISPER_BEAM_SIZE)
        text_parts = [seg.text.strip() for seg in segments]
    except Exception as e:
        log.error(
            "Failed to load Whisper model '%s': %s\n"
            "Ensure faster-whisper is installed and you have internet "
            "connectivity for initial model download.",
            model_size,
            e,
        )
        raise
    finally:
        sys.stdout = saved_stdout
        devnull.close()
    return " ".join(text_parts).strip()


def main() -> None:
    parser = argparse.ArgumentParser(description="Voice-to-text for Claude Code CLI")
    parser.add_argument(
        "--model",
        type=str,
        default=DEFAULT_MODEL_SIZE,
        choices=["tiny", "base", "small"],
        help="Whisper model size (default: base)",
    )
    parser.add_argument(
        "--device",
        type=int,
        default=None,
        help="Audio input device ID (use --list-devices to see available devices)",
    )
    parser.add_argument(
        "--list-devices",
        action="store_true",
        help="List available audio input devices and exit",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Enable debug logging to stderr",
    )
    args = parser.parse_args()

    handler = logging.StreamHandler(sys.stderr)
    handler.setFormatter(logging.Formatter("%(levelname)s: %(message)s"))
    log.addHandler(handler)
    log.setLevel(logging.DEBUG if args.debug else logging.INFO)

    if args.list_devices:
        devices = _get_input_devices()
        if not devices:
            log.error("No input devices found.")
            sys.exit(EXIT_ERROR)
        for dev in devices:
            log.info("  %d: %s", dev["id"], dev["name"])
        sys.exit(EXIT_SUCCESS)

    try:
        _acquire_lock()
    except LockAcquireError as e:
        log.error("%s", e)
        sys.exit(EXIT_ERROR)

    try:
        cfg = Config()
        cwd = os.getcwd()
        try:
            audio_data = record_with_gui(cwd, device_id=args.device, config=cfg)
        except RecordingCancelled:
            sys.exit(EXIT_ERROR)
        except RecordingError as e:
            log.error("%s", e)
            sys.exit(EXIT_ERROR)

        audio_duration = len(audio_data) / SAMPLE_RATE
        if cfg.transcribe_ratio is not None:
            est = audio_duration * cfg.transcribe_ratio
            log.info("Estimated transcription time: %.0fs", est)

        wav_path = None
        try:
            wav_path = save_wav(audio_data)
            t_start = time.time()
            transcript = transcribe(wav_path, model_size=args.model)
            t_elapsed = time.time() - t_start
            if audio_duration > 0:
                new_ratio = t_elapsed / audio_duration
                cfg.transcribe_ratio = new_ratio
                cfg.save()
                log.debug(
                    "transcription took %.1fs for %.1fs audio (ratio=%.4f)",
                    t_elapsed,
                    audio_duration,
                    new_ratio,
                )
        finally:
            if wav_path and os.path.exists(wav_path):
                os.remove(wav_path)

        if not transcript:
            log.warning("No speech detected in audio.")
            sys.exit(EXIT_ERROR)

        # stdout = transcript (what Claude Code reads)
        print(transcript)
    finally:
        _release_lock()


if __name__ == "__main__":
    main()
