#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""
Voice-to-text for Claude Code CLI.
Records audio from microphone, transcribes locally with faster-whisper.
Cross-platform: Linux (Fedora) and Windows 11.

A tkinter popup shows recording status with elapsed time and cwd context.
Supports pause/resume and cancel/done controls.

Usage:
    python3 voice.py [--model tiny|base|small] [--device DEVICE_ID]
    Transcript is printed to stdout.
"""

import argparse
import json
import logging
import os
import sys
import tempfile
import time
import uuid
import wave

try:
    import tkinter as tk
except ModuleNotFoundError:
    print(
        "Error: tkinter not found. Install it with:\n"
        "  Fedora: sudo dnf install python3-tkinter\n"
        "  Ubuntu/Debian: sudo apt install python3-tk\n"
        "  Windows/macOS: tkinter is included with standard Python",
        file=sys.stderr,
    )
    sys.exit(1)

import threading
from typing import Callable

import numpy as np
import sounddevice as sd

log = logging.getLogger(__name__)

# Background import of faster-whisper (heavy C++ bindings).
# Started early so the import finishes during recording.
_whisper_preload_started = False
_whisper_module_ready = threading.Event()
_WhisperModel = None


def _preload_whisper() -> None:
    """Import faster-whisper in a background thread."""
    global _WhisperModel
    try:
        from faster_whisper import WhisperModel

        _WhisperModel = WhisperModel
    except Exception:
        pass  # transcribe() will re-attempt and surface the error
    finally:
        _whisper_module_ready.set()


def start_whisper_preload() -> None:
    """Kick off the background import. Safe to call multiple times."""
    global _whisper_preload_started
    if _whisper_preload_started:
        return
    _whisper_preload_started = True
    t = threading.Thread(target=_preload_whisper, daemon=True)
    t.start()


APP_NAME = "claude-skill-voice"
CONFIG_FILENAME = "settings.json"
LOCK_FILENAME = "voice.lock"
CONFIG_KEY_WINDOW_X = "window_x"
CONFIG_KEY_WINDOW_Y = "window_y"
CONFIG_KEY_TRANSCRIBE_RATIO = "transcribe_ratio"

SAMPLE_RATE = 16000
AUDIO_CHANNELS = 1
AUDIO_DTYPE = "int16"
AUDIO_SAMPLE_WIDTH = 2
DEFAULT_MODEL_SIZE = "small"
WHISPER_BEAM_SIZE = 5
WHISPER_DEVICE = "cpu"
WHISPER_COMPUTE_TYPE = "int8"

EXIT_SUCCESS = 0
EXIT_ERROR = 1

MAX_PATH_DISPLAY_LENGTH = 60
TIMER_UPDATE_MS = 200

COLOR_RECORDING = "#cc0000"
COLOR_RECORDING_ACTIVE = "#990000"
COLOR_PAUSED = "#cc8800"
COLOR_PAUSED_ACTIVE = "#996600"
COLOR_DONE = "#228B22"
COLOR_DONE_ACTIVE = "#1a6b1a"
COLOR_MUTED = "#666666"

FONT_STATUS = ("sans-serif", 16, "bold")
FONT_TIMER = ("monospace", 24)
FONT_DETAIL = ("monospace", 9)
FONT_BUTTON = ("sans-serif", 12)

LEVEL_BAR_WIDTH = 260
LEVEL_BAR_HEIGHT = 8
LEVEL_UPDATE_MS = 50
LEVEL_COLOR = "#888888"
LEVEL_BG_COLOR = "#d0d0d0"

PROGRESS_BAR_WIDTH = 260
PROGRESS_BAR_HEIGHT = 18
PROGRESS_COLOR = COLOR_DONE
PROGRESS_BG_COLOR = "#d0d0d0"
PROGRESS_UPDATE_MS = 200
COLOR_TRANSCRIBING = "#4477cc"


class RecordingError(Exception):
    """Raised when audio recording fails."""


class RecordingCancelled(Exception):
    """Raised when the user cancels recording."""


class LockAcquireError(Exception):
    """Raised when the lock file cannot be acquired."""


def _config_path() -> str:
    """Return the path to the settings JSON file, platform-appropriate."""
    if sys.platform == "win32":
        base = os.environ.get("APPDATA", os.path.expanduser("~"))
    else:
        base = os.environ.get(
            "XDG_CONFIG_HOME", os.path.join(os.path.expanduser("~"), ".config")
        )
    return os.path.join(base, APP_NAME, CONFIG_FILENAME)


class Config:
    """Persistent settings backed by a JSON file."""

    def __init__(self, path: str | None = None):
        self._path = path or _config_path()
        self._data: dict = {}
        self._load()

    def _load(self) -> None:
        if not os.path.exists(self._path):
            return
        try:
            with open(self._path) as f:
                self._data = json.load(f)
        except (json.JSONDecodeError, OSError):
            self._data = {}

    def save(self) -> None:
        os.makedirs(os.path.dirname(self._path), exist_ok=True)
        tmp = self._path + ".tmp"
        with open(tmp, "w") as f:
            json.dump(self._data, f, indent=2)
        os.replace(tmp, self._path)

    @property
    def window_x(self) -> int | None:
        raw = self._data.get(CONFIG_KEY_WINDOW_X)
        return int(raw) if isinstance(raw, (int, float)) else None

    @window_x.setter
    def window_x(self, value: int) -> None:
        self._data[CONFIG_KEY_WINDOW_X] = value

    @property
    def window_y(self) -> int | None:
        raw = self._data.get(CONFIG_KEY_WINDOW_Y)
        return int(raw) if isinstance(raw, (int, float)) else None

    @window_y.setter
    def window_y(self, value: int) -> None:
        self._data[CONFIG_KEY_WINDOW_Y] = value

    @property
    def transcribe_ratio(self) -> float | None:
        raw = self._data.get(CONFIG_KEY_TRANSCRIBE_RATIO)
        if isinstance(raw, (int, float)) and raw > 0:
            return float(raw)
        return None

    @transcribe_ratio.setter
    def transcribe_ratio(self, value: float) -> None:
        self._data[CONFIG_KEY_TRANSCRIBE_RATIO] = round(value, 4)


def _lock_path() -> str:
    """Return path to the PID lockfile."""
    config_dir = os.path.dirname(_config_path())
    return os.path.join(config_dir, LOCK_FILENAME)


def _is_pid_alive(pid: int) -> bool:
    """Check if a process with the given PID is running."""
    if sys.platform == "win32":
        # os.kill(pid, 0) on Windows sends CTRL_C_EVENT (signal 0) to the
        # console process group, which kills the caller. Use OpenProcess instead.
        import ctypes

        PROCESS_QUERY_LIMITED_INFORMATION = 0x1000
        handle = ctypes.windll.kernel32.OpenProcess(
            PROCESS_QUERY_LIMITED_INFORMATION, False, pid
        )
        if handle:
            ctypes.windll.kernel32.CloseHandle(handle)
            return True
        return False
    try:
        os.kill(pid, 0)  # signal 0: check existence, does not kill
        return True
    except PermissionError:
        return True  # exists but we lack permission to signal it
    except OSError:
        return False


def _read_lock_pid() -> int | None:
    """Read and return the PID from the lockfile, or None if unreadable."""
    path = _lock_path()
    if not os.path.exists(path):
        return None
    try:
        with open(path) as f:
            return int(f.read().strip())
    except (ValueError, OSError):
        return None


def _write_lock_file(path: str, pid: int) -> None:
    """Atomically create lockfile with PID. Raises FileExistsError if exists."""
    fd = None
    try:
        fd = os.open(path, os.O_CREAT | os.O_EXCL | os.O_WRONLY)
        os.write(fd, str(pid).encode())
    finally:
        if fd is not None:
            os.close(fd)


def _acquire_lock() -> None:
    """Acquire the PID lockfile. Raises LockAcquireError if held by another.

    Uses O_CREAT|O_EXCL for atomic file creation to prevent race conditions.
    """
    path = _lock_path()
    my_pid = os.getpid()
    os.makedirs(os.path.dirname(path), exist_ok=True)

    # Fast path: try atomic create
    try:
        _write_lock_file(path, my_pid)
        log.debug("lock acquired: pid=%d", my_pid)
        return
    except FileExistsError:
        pass

    # Lock file exists — check who owns it
    lock_pid = _read_lock_pid()

    if lock_pid is not None and lock_pid == my_pid:
        log.debug("lock already owned by us: pid=%d", my_pid)
        return

    if lock_pid is not None and _is_pid_alive(lock_pid):
        log.debug("lock held by live process: pid=%d", lock_pid)
        raise LockAcquireError(
            "Another voice recording session is already running. "
            "Finish that session before starting a new one."
        )

    # Stale lock (process dead or bad PID) — remove and retry
    log.debug("removing stale lock: pid=%s", lock_pid)
    try:
        os.remove(path)
    except OSError:
        pass
    try:
        _write_lock_file(path, my_pid)
        log.debug("lock acquired after stale cleanup: pid=%d", my_pid)
    except FileExistsError:
        raise LockAcquireError(
            "Failed to acquire lock. Another session may have started."
        )


def _release_lock() -> None:
    """Remove the PID lockfile only if we own it."""
    lock_pid = _read_lock_pid()
    if lock_pid is not None and lock_pid != os.getpid():
        log.warning(
            "lock not owned by us (owner=%d, self=%d), not releasing",
            lock_pid,
            os.getpid(),
        )
        return
    try:
        os.remove(_lock_path())
        log.debug("lock released")
    except OSError:
        pass


def _home_relative_path(path: str) -> str:
    """Convert an absolute path to ~/relative form."""
    home = os.path.expanduser("~")
    if path == home or path.startswith(home + os.sep):
        return "~" + path[len(home) :]
    return path


def _truncate_path(path: str, *, max_length: int = MAX_PATH_DISPLAY_LENGTH) -> str:
    if len(path) > max_length:
        return "..." + path[-(max_length - 3) :]
    return path


def _get_default_input_device() -> int:
    """Return the sounddevice index of the system default input device."""
    default = sd.default.device[0]
    if default is None or default < 0:
        devices = sd.query_devices()
        for i, dev in enumerate(devices):
            if dev["max_input_channels"] > 0:
                return i
        raise RecordingError("No input devices found.")
    return int(default)


def _get_input_devices() -> list[dict]:
    devices = sd.query_devices()
    result = []
    for i, dev in enumerate(devices):
        if dev["max_input_channels"] > 0:
            result.append({"id": i, "name": dev["name"]})
    return result


def record_with_gui(
    cwd: str, *, device_id: int | None = None, config: Config | None = None
) -> tuple[np.ndarray, tk.Tk]:
    """Show a tkinter popup while recording. Returns (audio_data, root).

    On Done, the root window stays alive (mainloop exits via quit()) so it
    can be reused for the transcription progress display. The caller is
    responsible for eventually calling root.destroy().

    On Cancel, the root is destroyed and RecordingCancelled is raised.

    Raises:
        RecordingError: If no audio was captured.
        RecordingCancelled: If the user cancelled recording.
    """
    if config is None:
        config = Config()
    if device_id is None:
        device_id = _get_default_input_device()
        log.debug("resolved default input device: %d", device_id)

    chunks: list[np.ndarray] = []
    recording = True
    paused = False
    cancelled = False
    start_time = time.time()
    paused_elapsed = 0.0
    pause_start = 0.0

    callback_count = [0]
    current_level = [0.0]  # 0.0–1.0, updated by audio callback

    def audio_callback(indata, _frames, _time_info, status):
        callback_count[0] += 1
        if status:
            log.warning("audio_callback status: %s", status)
        if recording and not paused:
            chunks.append(indata.copy())
            peak = int(np.max(np.abs(indata)))
            current_level[0] = min(peak / 32768.0 * 4.0, 1.0)
            if callback_count[0] % 50 == 0:
                log.debug(
                    "callback #%d, chunks=%d, peak=%d",
                    callback_count[0],
                    len(chunks),
                    peak,
                )
        else:
            current_level[0] = 0.0

    try:
        stream = sd.InputStream(
            samplerate=SAMPLE_RATE,
            channels=AUDIO_CHANNELS,
            dtype=AUDIO_DTYPE,
            callback=audio_callback,
            device=device_id,
        )
    except Exception as e:
        log.error("Failed to access microphone: %s", e)
        sys.exit(EXIT_ERROR)

    root = tk.Tk()
    root.title("Claude Voice")
    root.attributes("-topmost", True)
    root.resizable(False, False)

    if config.window_x is not None and config.window_y is not None:
        root.geometry(f"+{config.window_x}+{config.window_y}")

    frame = tk.Frame(root, padx=20, pady=15)
    frame.pack()

    timer_frame = tk.Frame(frame)
    timer_frame.pack(pady=(10, 5))
    timer_frame.grid_columnconfigure(0, minsize=160)

    status_var = tk.StringVar(value="Recording:")
    status_label = tk.Label(
        timer_frame,
        textvariable=status_var,
        font=FONT_STATUS,
        fg=COLOR_RECORDING,
        width=11,
        anchor="w",
    )
    status_label.grid(row=0, column=0, sticky="w", padx=(0, 5))

    elapsed_var = tk.StringVar(value="0:00")
    tk.Label(timer_frame, textvariable=elapsed_var, font=FONT_STATUS).grid(
        row=0, column=1, sticky="e"
    )

    tk.Label(timer_frame, text="Transcribe:", font=FONT_STATUS, fg=COLOR_MUTED).grid(
        row=1, column=0, sticky="w", padx=(0, 5)
    )
    transcribe_est_var = tk.StringVar(value="unknown")
    tk.Label(
        timer_frame,
        textvariable=transcribe_est_var,
        font=FONT_STATUS,
        fg=COLOR_MUTED,
    ).grid(row=1, column=1, sticky="e")

    display_cwd = _truncate_path(_home_relative_path(cwd))
    tk.Label(frame, text=display_cwd, font=FONT_DETAIL, fg=COLOR_MUTED).pack()

    device_name = sd.query_devices(device_id)["name"]
    tk.Label(frame, text=f"Mic: {device_name}", font=FONT_DETAIL, fg=COLOR_MUTED).pack(
        pady=(0, 5)
    )

    level_canvas = tk.Canvas(
        frame,
        width=LEVEL_BAR_WIDTH,
        height=LEVEL_BAR_HEIGHT,
        bg=LEVEL_BG_COLOR,
        highlightthickness=0,
    )
    level_canvas.pack(pady=(0, 10))
    level_bar = level_canvas.create_rectangle(
        0, 0, 0, LEVEL_BAR_HEIGHT, fill=LEVEL_COLOR, width=0
    )

    button_frame = tk.Frame(frame)
    button_frame.pack()

    pending_after_ids: list[str] = []

    def _cancel_pending_afters():
        for after_id in pending_after_ids:
            try:
                root.after_cancel(after_id)
            except Exception:
                pass
        pending_after_ids.clear()

    def _save_window_pos():
        try:
            config.window_x = root.winfo_x()
            config.window_y = root.winfo_y()
            config.save()
        except Exception:
            pass

    def cancel_recording():
        nonlocal recording, cancelled
        recording = False
        cancelled = True
        _cancel_pending_afters()
        _save_window_pos()
        root.destroy()

    def toggle_pause():
        nonlocal paused, pause_start, paused_elapsed
        if paused:
            paused_elapsed += time.time() - pause_start
            paused = False
            status_var.set("Recording:")
            status_label.config(fg=COLOR_RECORDING)
            pause_btn.config(text="Pause")
            update_timer()
        else:
            pause_start = time.time()
            paused = True
            status_var.set("Paused:")
            status_label.config(fg=COLOR_PAUSED)
            pause_btn.config(text="Resume")

    def done_recording():
        nonlocal recording
        recording = False
        _cancel_pending_afters()
        _save_window_pos()
        root.quit()  # exit mainloop but keep window alive for progress

    btn_width = 7

    cancel_btn = tk.Button(
        button_frame,
        text="Cancel",
        font=FONT_BUTTON,
        command=cancel_recording,
        bg=COLOR_RECORDING,
        fg="white",
        activebackground=COLOR_RECORDING_ACTIVE,
        activeforeground="white",
        width=btn_width,
        pady=5,
    )
    cancel_btn.pack(side=tk.LEFT, padx=(0, 5))

    pause_btn = tk.Button(
        button_frame,
        text="Pause",
        font=FONT_BUTTON,
        command=toggle_pause,
        bg=COLOR_PAUSED,
        fg="white",
        activebackground=COLOR_PAUSED_ACTIVE,
        activeforeground="white",
        width=btn_width,
        pady=5,
    )
    pause_btn.pack(side=tk.LEFT, padx=(0, 5))

    done_btn = tk.Button(
        button_frame,
        text="Done",
        font=FONT_BUTTON,
        command=done_recording,
        bg=COLOR_DONE,
        fg="white",
        activebackground=COLOR_DONE_ACTIVE,
        activeforeground="white",
        width=btn_width,
        pady=5,
    )
    done_btn.pack(side=tk.LEFT)

    root.bind("<Escape>", lambda _e: cancel_recording())
    root.bind("<space>", lambda _e: toggle_pause())
    root.bind("<Return>", lambda _e: done_recording())

    saved_ratio = config.transcribe_ratio

    def update_timer():
        if recording and not paused:
            elapsed = int(time.time() - start_time - paused_elapsed)
            mins, secs = divmod(elapsed, 60)
            elapsed_var.set(f"{mins}:{secs:02d}")
            if saved_ratio is not None:
                est = int(elapsed * saved_ratio)
                est_mins, est_secs = divmod(est, 60)
                transcribe_est_var.set(f"{est_mins}:{est_secs:02d}")
            after_id = root.after(TIMER_UPDATE_MS, update_timer)
            pending_after_ids.append(after_id)

    def update_level():
        if recording:
            level = current_level[0] if not paused else 0.0
            bar_width = int(level * LEVEL_BAR_WIDTH)
            level_canvas.coords(level_bar, 0, 0, bar_width, LEVEL_BAR_HEIGHT)
            after_id = root.after(LEVEL_UPDATE_MS, update_level)
            pending_after_ids.append(after_id)

    root.protocol("WM_DELETE_WINDOW", cancel_recording)

    try:
        stream.start()
        update_timer()
        update_level()
        root.mainloop()
    finally:
        stream.stop()
        stream.close()

    log.debug(
        "recording ended: chunks=%d, callback_count=%d, cancelled=%s",
        len(chunks),
        callback_count[0],
        cancelled,
    )

    if cancelled:
        raise RecordingCancelled("Recording cancelled.")

    if not chunks:
        raise RecordingError("No audio captured.")

    audio_data = np.concatenate(chunks, axis=0)
    duration = len(audio_data) / SAMPLE_RATE
    log.info("Captured %.1fs of audio.", duration)
    return audio_data, root


def save_wav_to(audio_data: np.ndarray, path: str) -> None:
    """Save audio data to a WAV file at the given path."""
    with wave.open(path, "wb") as wf:
        wf.setnchannels(AUDIO_CHANNELS)
        wf.setsampwidth(AUDIO_SAMPLE_WIDTH)
        wf.setframerate(SAMPLE_RATE)
        wf.writeframes(audio_data.tobytes())


def save_wav(audio_data: np.ndarray) -> str:
    """Save audio to a temporary WAV file. Returns the path."""
    file_id = uuid.uuid4().hex[:8]
    wav_path = os.path.join(tempfile.gettempdir(), f"claude_voice_{file_id}.wav")
    save_wav_to(audio_data, wav_path)
    return wav_path


def transcribe_with_progress(
    wav_path: str,
    *,
    root: tk.Tk,
    model_size: str = DEFAULT_MODEL_SIZE,
    audio_duration: float = 0.0,
    transcribe_ratio: float | None = None,
) -> str:
    """Run transcription with a tkinter progress window.

    Reuses an existing tk.Tk root (from record_with_gui) to avoid creating
    a second Tcl interpreter, which causes Tcl_AsyncDelete crashes on
    Windows. Clears the existing widgets and replaces them with progress UI.

    The root is destroyed when transcription completes or fails.

    Returns the transcript text.
    """
    # Clear recording widgets, reuse the same window
    for widget in root.winfo_children():
        widget.destroy()

    frame = tk.Frame(root, padx=20, pady=15)
    frame.pack()

    status_label = tk.Label(
        frame,
        text="Transcribing...",
        font=FONT_STATUS,
        fg=COLOR_TRANSCRIBING,
    )
    status_label.pack(pady=(0, 5))

    # Estimate row
    est_frame = tk.Frame(frame)
    est_frame.pack(pady=(0, 5))

    elapsed_var = tk.StringVar(value="0:00")
    est_var = tk.StringVar()
    has_estimate = transcribe_ratio is not None and audio_duration > 0
    if has_estimate and transcribe_ratio is not None:
        est_total = int(audio_duration * transcribe_ratio)
        est_m, est_s = divmod(est_total, 60)
        est_var.set(f"~{est_m}:{est_s:02d}")

    tk.Label(est_frame, text="Elapsed:", font=FONT_DETAIL, fg=COLOR_MUTED).grid(
        row=0, column=0, sticky="w", padx=(0, 5)
    )
    tk.Label(est_frame, textvariable=elapsed_var, font=FONT_DETAIL).grid(
        row=0, column=1, sticky="e"
    )
    if has_estimate:
        tk.Label(est_frame, text="Est:", font=FONT_DETAIL, fg=COLOR_MUTED).grid(
            row=0, column=2, sticky="w", padx=(10, 5)
        )
        tk.Label(
            est_frame, textvariable=est_var, font=FONT_DETAIL, fg=COLOR_MUTED
        ).grid(row=0, column=3, sticky="e")

    # Progress bar
    progress_canvas = tk.Canvas(
        frame,
        width=PROGRESS_BAR_WIDTH,
        height=PROGRESS_BAR_HEIGHT,
        bg=PROGRESS_BG_COLOR,
        highlightthickness=0,
    )
    progress_canvas.pack(pady=(5, 10))
    progress_bar = progress_canvas.create_rectangle(
        0, 0, 0, PROGRESS_BAR_HEIGHT, fill=PROGRESS_COLOR, width=0
    )

    percent_var = tk.StringVar(value="0%")
    tk.Label(frame, textvariable=percent_var, font=FONT_DETAIL, fg=COLOR_MUTED).pack()

    # Shared state between threads
    progress_fraction = [0.0]
    transcription_result: list[str | None] = [None]
    transcription_error: list[Exception | None] = [None]
    transcription_done = threading.Event()
    t_start = time.time()

    def on_progress(fraction: float) -> None:
        progress_fraction[0] = fraction

    def run_transcription() -> None:
        try:
            result = transcribe(
                wav_path,
                model_size=model_size,
                progress_callback=on_progress,
            )
            transcription_result[0] = result
        except Exception as e:
            transcription_error[0] = e
        finally:
            transcription_done.set()

    def update_ui() -> None:
        # Update elapsed time
        elapsed = int(time.time() - t_start)
        mins, secs = divmod(elapsed, 60)
        elapsed_var.set(f"{mins}:{secs:02d}")

        # Update progress bar
        frac = progress_fraction[0]
        bar_width = int(frac * PROGRESS_BAR_WIDTH)
        progress_canvas.coords(progress_bar, 0, 0, bar_width, PROGRESS_BAR_HEIGHT)
        percent_var.set(f"{int(frac * 100)}%")

        if transcription_done.is_set():
            root.destroy()
        else:
            root.after(PROGRESS_UPDATE_MS, update_ui)

    # Prevent closing the window from killing transcription
    root.protocol("WM_DELETE_WINDOW", lambda: None)

    thread = threading.Thread(target=run_transcription, daemon=True)
    thread.start()
    update_ui()
    root.mainloop()

    thread.join(timeout=5)

    if transcription_error[0] is not None:
        raise transcription_error[0]

    return transcription_result[0] or ""


def transcribe(
    wav_path: str,
    *,
    model_size: str = DEFAULT_MODEL_SIZE,
    progress_callback: "Callable[[float], None] | None" = None,
) -> str:
    """Transcribe WAV file using faster-whisper.

    Args:
        wav_path: Path to the WAV file.
        model_size: Whisper model size.
        progress_callback: Called with progress fraction (0.0-1.0) after each
            segment, based on segment end time / audio duration.
    """
    log.info("Transcribing with model '%s'...", model_size)
    if _whisper_preload_started:
        _whisper_module_ready.wait()
    model_cls = _WhisperModel if _whisper_preload_started and _WhisperModel else None
    if model_cls is None:
        from faster_whisper import WhisperModel as _WM

        model_cls = _WM

    # Get audio duration for progress tracking
    audio_duration = 0.0
    try:
        with wave.open(wav_path, "rb") as wf:
            audio_duration = wf.getnframes() / wf.getframerate()
    except Exception:
        pass

    # Suppress stdout from ctranslate2/faster-whisper progress output
    devnull = open(os.devnull, "w")  # noqa: SIM115
    saved_stdout = sys.stdout
    sys.stdout = devnull
    try:
        model = model_cls(
            model_size, device=WHISPER_DEVICE, compute_type=WHISPER_COMPUTE_TYPE
        )
        segments, _ = model.transcribe(wav_path, beam_size=WHISPER_BEAM_SIZE)
        text_parts = []
        for seg in segments:
            text_parts.append(seg.text.strip())
            if progress_callback and audio_duration > 0:
                fraction = min(seg.end / audio_duration, 1.0)
                progress_callback(fraction)
    except Exception as e:
        log.error(
            "Failed to load Whisper model '%s': %s\n"
            "Ensure faster-whisper is installed and you have internet "
            "connectivity for initial model download.",
            model_size,
            e,
        )
        raise
    finally:
        sys.stdout = saved_stdout
        devnull.close()
    if progress_callback:
        progress_callback(1.0)
    return " ".join(text_parts).strip()


def main() -> None:
    parser = argparse.ArgumentParser(description="Voice-to-text for Claude Code CLI")
    parser.add_argument(
        "--model",
        type=str,
        default=DEFAULT_MODEL_SIZE,
        choices=["tiny", "base", "small"],
        help="Whisper model size (default: base)",
    )
    parser.add_argument(
        "--device",
        type=int,
        default=None,
        help="Audio input device ID (use --list-devices to see available devices)",
    )
    parser.add_argument(
        "--list-devices",
        action="store_true",
        help="List available audio input devices and exit",
    )
    parser.add_argument(
        "--wav-output",
        type=str,
        default=None,
        metavar="PATH",
        help="Save recorded audio to this WAV file (kept after transcription)",
    )
    parser.add_argument(
        "--wav-input",
        type=str,
        default=None,
        metavar="PATH",
        help="Transcribe from an existing WAV file instead of recording",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Enable debug logging to stderr",
    )
    args = parser.parse_args()

    handler = logging.StreamHandler(sys.stderr)
    handler.setFormatter(logging.Formatter("%(levelname)s: %(message)s"))
    log.addHandler(handler)
    log.setLevel(logging.DEBUG if args.debug else logging.INFO)

    if args.list_devices:
        devices = _get_input_devices()
        if not devices:
            log.error("No input devices found.")
            sys.exit(EXIT_ERROR)
        for dev in devices:
            log.info("  %d: %s", dev["id"], dev["name"])
        sys.exit(EXIT_SUCCESS)

    # --wav-input: transcribe-only mode (no recording, no lock, no GUI)
    if args.wav_input:
        if not os.path.exists(args.wav_input):
            log.error("WAV file not found: %s", args.wav_input)
            sys.exit(EXIT_ERROR)
        start_whisper_preload()
        t_start = time.time()
        transcript = transcribe(args.wav_input, model_size=args.model)
        t_elapsed = time.time() - t_start
        try:
            with wave.open(args.wav_input, "rb") as wf:
                audio_duration = wf.getnframes() / wf.getframerate()
        except Exception:
            audio_duration = 0.0
        log.info(
            "Transcribed %.1fs audio in %.1fs (model=%s)",
            audio_duration,
            t_elapsed,
            args.model,
        )
        print(transcript)
        sys.exit(EXIT_SUCCESS)

    try:
        _acquire_lock()
    except LockAcquireError as e:
        log.error("%s", e)
        sys.exit(EXIT_ERROR)

    try:
        # Start importing faster-whisper in background while user records
        start_whisper_preload()
        cfg = Config()
        cwd = os.getcwd()
        gui_root: tk.Tk | None = None
        try:
            audio_data, gui_root = record_with_gui(
                cwd, device_id=args.device, config=cfg
            )
        except RecordingCancelled:
            print("[CANCEL]")
            sys.exit(EXIT_SUCCESS)
        except RecordingError as e:
            log.error("%s", e)
            sys.exit(EXIT_ERROR)

        audio_duration = len(audio_data) / SAMPLE_RATE
        if cfg.transcribe_ratio is not None:
            est = audio_duration * cfg.transcribe_ratio
            log.info("Estimated transcription time: %.0fs", est)

        wav_path = None
        delete_wav = True
        try:
            if args.wav_output:
                wav_path = os.path.abspath(args.wav_output)
                save_wav_to(audio_data, wav_path)
                log.info("Saved audio to %s", wav_path)
                delete_wav = False
            else:
                wav_path = save_wav(audio_data)

            t_start = time.time()
            transcript = transcribe_with_progress(
                wav_path,
                root=gui_root,
                model_size=args.model,
                audio_duration=audio_duration,
                transcribe_ratio=cfg.transcribe_ratio,
            )
            gui_root = None  # transcribe_with_progress destroyed it
            t_elapsed = time.time() - t_start
            if audio_duration > 0:
                new_ratio = t_elapsed / audio_duration
                cfg.transcribe_ratio = new_ratio
                cfg.save()
                log.debug(
                    "transcription took %.1fs for %.1fs audio (ratio=%.4f)",
                    t_elapsed,
                    audio_duration,
                    new_ratio,
                )
        finally:
            if delete_wav and wav_path and os.path.exists(wav_path):
                os.remove(wav_path)
            if gui_root is not None:
                try:
                    gui_root.destroy()
                except Exception:
                    pass

        if not transcript:
            print("[DONE]")
            log.warning("No speech detected in audio.")
            sys.exit(EXIT_SUCCESS)

        # stdout: status line then transcript (what Claude Code reads)
        print("[DONE]")
        print(transcript)
    finally:
        _release_lock()


if __name__ == "__main__":
    main()
