# Generated By: Claude Code (Claude Opus 4.6)
"""Whisper model management and transcription.

Handles model caching, background preloading, and transcription of WAV files
and raw audio data. Used by voice.py and chunks.py.
"""

import logging
import os
import sys
import tempfile
import threading
import uuid
import wave

import numpy as np

from typing import Callable

logger = logging.getLogger(__name__)

SAMPLE_RATE = 16000
AUDIO_CHANNELS = 1
AUDIO_SAMPLE_WIDTH = 2
DEFAULT_MODEL_SIZE = "small"
WHISPER_BEAM_SIZE = 5
WHISPER_DEVICE = "cpu"
WHISPER_COMPUTE_TYPE = "int8"

# Background import of faster-whisper (heavy C++ bindings).
# Started early so the import finishes during recording.
_whisper_preload_started = False
_whisper_module_ready = threading.Event()
_WhisperModel = None

# Model instance cache — avoids reloading for each chunk.
_cached_model = None
_cached_model_size: str | None = None


def _preload_whisper() -> None:
    """Import faster-whisper in a background thread."""
    global _WhisperModel
    try:
        from faster_whisper import WhisperModel

        _WhisperModel = WhisperModel
    except Exception:
        pass  # transcribe functions will re-attempt and surface the error
    finally:
        _whisper_module_ready.set()


def start_whisper_preload() -> None:
    """Kick off the background import. Safe to call multiple times."""
    global _whisper_preload_started
    if _whisper_preload_started:
        return
    _whisper_preload_started = True
    t = threading.Thread(target=_preload_whisper, daemon=True)
    t.start()


def _get_model_class():
    """Return the WhisperModel class, waiting for preload if needed."""
    if _whisper_preload_started:
        _whisper_module_ready.wait()
    model_cls = _WhisperModel if _whisper_preload_started and _WhisperModel else None
    if model_cls is None:
        from faster_whisper import WhisperModel as _WM

        model_cls = _WM
    return model_cls


def _get_or_create_model(model_size: str = DEFAULT_MODEL_SIZE):
    """Return a cached WhisperModel instance, creating one if needed.

    The model is cached at module level and reused across calls with the
    same model_size. This avoids the expensive model load for each chunk
    in chunked transcription.
    """
    global _cached_model, _cached_model_size

    if _cached_model is not None and _cached_model_size == model_size:
        return _cached_model

    model_cls = _get_model_class()

    # Suppress stdout from ctranslate2/faster-whisper progress output
    devnull = open(os.devnull, "w")  # noqa: SIM115
    saved_stdout = sys.stdout
    sys.stdout = devnull
    try:
        model = model_cls(
            model_size, device=WHISPER_DEVICE, compute_type=WHISPER_COMPUTE_TYPE
        )
    finally:
        sys.stdout = saved_stdout
        devnull.close()

    _cached_model = model
    _cached_model_size = model_size
    return model


def save_wav_to(audio_data: np.ndarray, path: str) -> None:
    """Save audio data to a WAV file at the given path."""
    with wave.open(path, "wb") as wf:
        wf.setnchannels(AUDIO_CHANNELS)
        wf.setsampwidth(AUDIO_SAMPLE_WIDTH)
        wf.setframerate(SAMPLE_RATE)
        wf.writeframes(audio_data.tobytes())


def save_wav(audio_data: np.ndarray) -> str:
    """Save audio to a temporary WAV file. Returns the path."""
    file_id = uuid.uuid4().hex[:8]
    wav_path = os.path.join(tempfile.gettempdir(), f"claude_voice_{file_id}.wav")
    save_wav_to(audio_data, wav_path)
    return wav_path


def transcribe_wav(
    wav_path: str,
    *,
    model_size: str = DEFAULT_MODEL_SIZE,
    progress_callback: Callable[[float], None] | None = None,
) -> str:
    """Transcribe a WAV file using faster-whisper.

    Args:
        wav_path: Path to the WAV file.
        model_size: Whisper model size.
        progress_callback: Called with progress fraction (0.0-1.0) after each
            segment, based on segment end time / audio duration.
    """
    logger.info("Transcribing with model '%s'...", model_size)

    # Get audio duration for progress tracking
    audio_duration = 0.0
    try:
        with wave.open(wav_path, "rb") as wf:
            audio_duration = wf.getnframes() / wf.getframerate()
    except Exception:
        pass

    try:
        model = _get_or_create_model(model_size)
        # Suppress stdout during transcription
        devnull = open(os.devnull, "w")  # noqa: SIM115
        saved_stdout = sys.stdout
        sys.stdout = devnull
        try:
            segments, _ = model.transcribe(wav_path, beam_size=WHISPER_BEAM_SIZE)
            text_parts = []
            for seg in segments:
                text_parts.append(seg.text.strip())
                if progress_callback and audio_duration > 0:
                    fraction = min(seg.end / audio_duration, 1.0)
                    progress_callback(fraction)
        finally:
            sys.stdout = saved_stdout
            devnull.close()
    except Exception as e:
        logger.error(
            "Failed to load Whisper model '%s': %s\n"
            "Ensure faster-whisper is installed and you have internet "
            "connectivity for initial model download.",
            model_size,
            e,
        )
        raise
    if progress_callback:
        progress_callback(1.0)
    return " ".join(text_parts).strip()


def transcribe_audio(
    audio_data: np.ndarray,
    *,
    model_size: str = DEFAULT_MODEL_SIZE,
    progress_callback: Callable[[float], None] | None = None,
) -> str:
    """Transcribe raw audio data (int16 numpy array) using faster-whisper.

    Saves to a temp WAV, transcribes, and cleans up. Used by ChunkManager
    for individual chunks.
    """
    wav_path = save_wav(audio_data)
    try:
        return transcribe_wav(
            wav_path, model_size=model_size, progress_callback=progress_callback
        )
    finally:
        if os.path.exists(wav_path):
            os.remove(wav_path)
